// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.tui.suggestion@1";
pub const DESCRIPTOR_VERSION: &str = "1.2.0";
pub const PORTABLE: bool = false;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SUGGESTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SUGGESTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_suggestion { () => { "{\"capability_id\":\"lenso.tui.suggestion@1\",\"descriptor_version\":\"1.2.0\",\"operations\":[\"snapshot\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_suggestion_client { () => { "{\"capability_id\":\"lenso.tui.suggestion@1\",\"descriptor_version\":\"1.2.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_suggestion_client { () => { "{\"capability_id\":\"lenso.tui.suggestion@1\",\"descriptor_version\":\"1.2.0\",\"cardinality\":\"many\"}" }; }

pub const SNAPSHOT_OPERATION: &str = "snapshot";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotResponse {
    #[serde(rename = "suggestions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub suggestions: Vec<SuggestionItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SuggestionItem {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "insert_text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub insert_text: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: SuggestionKind,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SuggestionKind {
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "prompt")]
    Prompt,
    #[serde(rename = "resource")]
    Resource,
    #[serde(rename = "skill")]
    Skill,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SnapshotError {
    SnapshotInvalid,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Suggestion;
impl RequestCapability for Suggestion {
    type Request = SnapshotRequest;
    type Response = SnapshotResponse;
    type DomainError = SnapshotError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SNAPSHOT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SuggestionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).snapshot(context, request)
    }
}

impl serde::Serialize for SnapshotError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::SnapshotInvalid => serializer.serialize_str("snapshot_invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SnapshotError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "snapshot_invalid" => Ok(Self::SnapshotInvalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_snapshot_request(value: &SnapshotRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_request(wire: &str) -> Result<SnapshotRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_response(value: &SnapshotResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_response(wire: &str) -> Result<SnapshotResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_error(value: &SnapshotError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_error(wire: &str) -> Result<SnapshotError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoSuggestionSnapshotResult {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure>;
}
impl __LensoIntoSuggestionSnapshotResult for Result<SnapshotResponse, SnapshotError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoSuggestionSnapshotResult for Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { self }
}
impl __LensoIntoSuggestionSnapshotResult for Result<SnapshotResponse, lenso_plugin_authoring::PluginError<SnapshotError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoSuggestionSnapshotResult for Result<SnapshotResponse, SuggestionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(SuggestionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(SuggestionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait SuggestionProvider: fmt::Debug + 'static {
    fn snapshot(&self, context: InvocationContext, request: SnapshotRequest) -> NativeRequestFuture<Suggestion>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_suggestion {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportSuggestion;
        impl $crate::SuggestionProvider for $plugin {
        fn snapshot(&self, context: __LensoNativeSupportSuggestion::InvocationContext, request: $crate::SnapshotRequest) -> __LensoNativeSupportSuggestion::NativeRequestFuture<$crate::Suggestion> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::snapshot(&plugin, context, request).await;
                $crate::__LensoIntoSuggestionSnapshotResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct SuggestionRequestEndpoint { provider: Rc<dyn SuggestionProvider> }

#[derive(Debug)]
pub struct SuggestionEndpoint<P: SuggestionProvider> { provider: Rc<P>, request_endpoint: SuggestionRequestEndpoint }
impl<P: SuggestionProvider> SuggestionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SuggestionProvider> = provider.clone();
        Self { provider, request_endpoint: SuggestionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SuggestionProvider> NativeRequestEndpoint for SuggestionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SNAPSHOT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SNAPSHOT_OPERATION => {
                let Ok(request) = request.downcast::<SnapshotRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).snapshot(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_suggestion {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::SuggestionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_suggestion {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_suggestion!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SuggestionClient {
    snapshot: NativeRequestHandle<Suggestion>,
}
impl SuggestionClient {
    pub fn new(handle: NativeRequestHandle<Suggestion>) -> Self {
        Self { snapshot: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn snapshot(&self, request: SnapshotRequest) -> Result<SnapshotResponse, SuggestionInvocationError> {
        self.snapshot.invoke(SNAPSHOT_OPERATION, request).await
            .map_err(SuggestionInvocationError::Runtime)?
            .map_err(SuggestionInvocationError::Domain)
    }

    pub async fn snapshot_with_context(&self, context: InvocationContext, request: SnapshotRequest) -> Result<SnapshotResponse, SuggestionInvocationError> {
        self.snapshot.invoke_with_context(SNAPSHOT_OPERATION, context, request).await
            .map_err(SuggestionInvocationError::Runtime)?
            .map_err(SuggestionInvocationError::Domain)
    }
}

impl CapabilityClient for SuggestionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            snapshot: dependencies.one::<Suggestion>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for SuggestionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    snapshot: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Suggestion>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SuggestionInvocationError {
    Domain(SnapshotError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct SuggestionGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> SuggestionGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[SNAPSHOT_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn snapshot(&self, request: &SnapshotRequest) -> Result<SnapshotResponse, lenso_guest_sdk::GuestError<SnapshotError>> {
        self.capability.request(SNAPSHOT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct SuggestionJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for SuggestionJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn request_operations(&self) -> &'static [&'static str] { &[SNAPSHOT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SNAPSHOT_OPERATION => {
                let value = request.downcast_ref::<SnapshotRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SNAPSHOT_OPERATION => serde_json::from_value::<SnapshotResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SNAPSHOT_OPERATION => serde_json::from_value::<SnapshotError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            SNAPSHOT_OPERATION => {
                let request = serde_json::from_value::<SnapshotRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<Suggestion>()?;
                    match handle.invoke_with_context(SNAPSHOT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
