// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.plugin-selection-authority@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:d8f209ae8e6a25529be23d7be7c0d51eefba00247364b19a9c922aaf89e6ed87";
pub const PORTABLE: bool = false;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const PLUGIN_SELECTION_AUTHORITY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PLUGIN_SELECTION_AUTHORITY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const PLUGIN_SELECTION_AUTHORITY_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const PLUGIN_SELECTION_AUTHORITY_CONTRACT: CapabilityReference<PluginSelectionAuthorityClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_plugin_selection_authority { () => { "{\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"set_enabled\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_plugin_selection_authority_client {
    () => { "{\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_plugin_selection_authority_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_plugin_selection_authority_client {
    () => { "{\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.plugin-selection-authority@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const SET_ENABLED_OPERATION: &str = "set_enabled";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetEnabledRequest {
    #[serde(rename = "enabled")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub enabled: bool,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub instance: String,
    #[serde(rename = "plugin_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub plugin_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SetEnabledResponse {
    #[serde(rename = "authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub authority: AuthoritySource,
    #[serde(rename = "base_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub base_revision: String,
    #[serde(rename = "enabled")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub enabled: bool,
    #[serde(rename = "instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub instance: String,
    #[serde(rename = "plugin_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub plugin_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "schema")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub schema: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AuthoritySource {
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "reference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reference: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SetEnabledError {
    AlreadySelected,
    Conflict,
    InvalidRequest,
    NotDisableable,
    NotFound,
    Unsupported,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PluginSelectionAuthority;
impl RequestCapability for PluginSelectionAuthority {
    type Request = SetEnabledRequest;
    type Response = SetEnabledResponse;
    type DomainError = SetEnabledError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SET_ENABLED_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PluginSelectionAuthorityRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).set_enabled(context, request)
    }
}

impl serde::Serialize for SetEnabledError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::AlreadySelected => serializer.serialize_str("already_selected"),
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotDisableable => serializer.serialize_str("not_disableable"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unsupported => serializer.serialize_str("unsupported"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SetEnabledError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "already_selected" => Ok(Self::AlreadySelected),
                "conflict" => Ok(Self::Conflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_disableable" => Ok(Self::NotDisableable),
                "not_found" => Ok(Self::NotFound),
                "unsupported" => Ok(Self::Unsupported),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_set_enabled_request(value: &SetEnabledRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_enabled_request(wire: &str) -> Result<SetEnabledRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_enabled_response(value: &SetEnabledResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_enabled_response(wire: &str) -> Result<SetEnabledResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_set_enabled_error(value: &SetEnabledError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_set_enabled_error(wire: &str) -> Result<SetEnabledError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPluginSelectionAuthoritySetEnabledResult {
    fn __lenso_into_result(self) -> Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure>;
}
impl __LensoIntoPluginSelectionAuthoritySetEnabledResult for Result<SetEnabledResponse, SetEnabledError> {
    fn __lenso_into_result(self) -> Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPluginSelectionAuthoritySetEnabledResult for Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure> { self }
}
impl __LensoIntoPluginSelectionAuthoritySetEnabledResult for Result<SetEnabledResponse, lenso_plugin_authoring::PluginError<SetEnabledError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPluginSelectionAuthoritySetEnabledResult for Result<SetEnabledResponse, PluginSelectionAuthorityInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SetEnabledResponse, SetEnabledError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PluginSelectionAuthorityInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PluginSelectionAuthorityInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PluginSelectionAuthorityProvider: fmt::Debug + 'static {
    fn set_enabled(&self, context: InvocationContext, request: SetEnabledRequest) -> NativeRequestFuture<PluginSelectionAuthority>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_plugin_selection_authority {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPluginSelectionAuthority;
        impl $crate::PluginSelectionAuthorityProvider for $plugin {
        fn set_enabled(&self, context: __LensoNativeSupportPluginSelectionAuthority::InvocationContext, request: $crate::SetEnabledRequest) -> __LensoNativeSupportPluginSelectionAuthority::NativeRequestFuture<$crate::PluginSelectionAuthority> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::set_enabled(&plugin, context, request).await;
                $crate::__LensoIntoPluginSelectionAuthoritySetEnabledResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_plugin_selection_authority {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPluginSelectionAuthority;
        impl $crate::PluginSelectionAuthorityProvider for $object {
        fn set_enabled(&self, context: __LensoNativeSupportPluginSelectionAuthority::InvocationContext, request: $crate::SetEnabledRequest) -> __LensoNativeSupportPluginSelectionAuthority::NativeRequestFuture<$crate::PluginSelectionAuthority> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::set_enabled(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoPluginSelectionAuthoritySetEnabledResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_plugin_selection_authority {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPluginSelectionAuthority;
        impl $crate::PluginSelectionAuthorityProvider for $object {
        fn set_enabled(&self, context: __LensoNativeSupportPluginSelectionAuthority::InvocationContext, request: $crate::SetEnabledRequest) -> __LensoNativeSupportPluginSelectionAuthority::NativeRequestFuture<$crate::PluginSelectionAuthority> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::PluginSelectionAuthorityProvider>::set_enabled(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct PluginSelectionAuthorityRequestEndpoint { provider: Rc<dyn PluginSelectionAuthorityProvider> }

#[derive(Debug)]
pub struct PluginSelectionAuthorityEndpoint<P: PluginSelectionAuthorityProvider> { provider: Rc<P>, request_endpoint: PluginSelectionAuthorityRequestEndpoint }
impl<P: PluginSelectionAuthorityProvider> PluginSelectionAuthorityEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PluginSelectionAuthorityProvider> = provider.clone();
        Self { provider, request_endpoint: PluginSelectionAuthorityRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PluginSelectionAuthorityProvider> NativeRequestEndpoint for PluginSelectionAuthorityEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SET_ENABLED_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SET_ENABLED_OPERATION => {
                let Ok(request) = request.downcast::<SetEnabledRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).set_enabled(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_plugin_selection_authority {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PluginSelectionAuthorityEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_plugin_selection_authority {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_plugin_selection_authority!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct PluginSelectionAuthorityClient {
    set_enabled: NativeRequestHandle<PluginSelectionAuthority>,
}
impl PluginSelectionAuthorityClient {
    pub fn new(handle: NativeRequestHandle<PluginSelectionAuthority>) -> Self {
        Self { set_enabled: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn set_enabled(&self, request: SetEnabledRequest) -> Result<SetEnabledResponse, PluginSelectionAuthorityInvocationError> {
        self.set_enabled.invoke(SET_ENABLED_OPERATION, request).await
            .map_err(PluginSelectionAuthorityInvocationError::Runtime)?
            .map_err(PluginSelectionAuthorityInvocationError::Domain)
    }

    pub async fn set_enabled_with_context(&self, context: InvocationContext, request: SetEnabledRequest) -> Result<SetEnabledResponse, PluginSelectionAuthorityInvocationError> {
        self.set_enabled.invoke_with_context(SET_ENABLED_OPERATION, context, request).await
            .map_err(PluginSelectionAuthorityInvocationError::Runtime)?
            .map_err(PluginSelectionAuthorityInvocationError::Domain)
    }
}

impl CapabilityClient for PluginSelectionAuthorityClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            set_enabled: dependencies.one::<PluginSelectionAuthority>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PluginSelectionAuthorityClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    set_enabled: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PluginSelectionAuthority>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PluginSelectionAuthorityInvocationError {
    Domain(SetEnabledError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct PluginSelectionAuthorityGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> PluginSelectionAuthorityGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[SET_ENABLED_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn set_enabled(&self, request: &SetEnabledRequest) -> Result<SetEnabledResponse, lenso_guest_sdk::GuestError<SetEnabledError>> {
        self.capability.request(SET_ENABLED_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct PluginSelectionAuthorityJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for PluginSelectionAuthorityJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[SET_ENABLED_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SET_ENABLED_OPERATION => {
                let value = request.downcast_ref::<SetEnabledRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SET_ENABLED_OPERATION => serde_json::from_value::<SetEnabledResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SET_ENABLED_OPERATION => serde_json::from_value::<SetEnabledError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            SET_ENABLED_OPERATION => {
                let request = serde_json::from_value::<SetEnabledRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<PluginSelectionAuthority>()?;
                    match handle.invoke_with_context(SET_ENABLED_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
