// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.user-interaction@2";
pub const DESCRIPTOR_VERSION: &str = "2.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:7fe3b0e843eec7ce41511b4da640eb1444417678e8a3a3f853a3b84df26af41b";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const USER_INTERACTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const USER_INTERACTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const USER_INTERACTION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const USER_INTERACTION_CONTRACT: CapabilityReference<UserInteractionClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_user_interaction { () => { "{\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"operations\":[\"answer\",\"ask\",\"pending\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_user_interaction_client {
    () => { "{\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_user_interaction_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_user_interaction_client {
    () => { "{\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.user-interaction@2\",\"descriptor_version\":\"2.0.0\",\"cardinality\":\"many\"}") };
}

pub const ANSWER_OPERATION: &str = "answer";
pub const ASK_OPERATION: &str = "ask";
pub const PENDING_OPERATION: &str = "pending";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AnswerRequest {
    #[serde(rename = "answers")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub answers: Vec<InteractionAnswer>,
    #[serde(rename = "interaction_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub interaction_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InteractionAnswer {
    #[serde(rename = "other")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub other: OptionalValue<String>,
    #[serde(rename = "question_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub question_id: String,
    #[serde(rename = "selected_option_ids")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub selected_option_ids: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AnswerResponse {

}

#[derive(Clone, Debug, PartialEq)]
pub enum AnswerError {
    InvalidAnswer,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AskRequest {
    #[serde(rename = "interaction_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub interaction_id: String,
    #[serde(rename = "questions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub questions: Vec<InteractionQuestion>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InteractionQuestion {
    #[serde(rename = "header")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub header: String,
    #[serde(rename = "multi_select")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub multi_select: bool,
    #[serde(rename = "options")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub options: Vec<InteractionOption>,
    #[serde(rename = "prompt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub prompt: String,
    #[serde(rename = "question_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub question_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InteractionOption {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "option_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub option_id: String,
    #[serde(rename = "preview")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub preview: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AskResponse {
    #[serde(rename = "answers")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub answers: Vec<InteractionAnswer>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AskError {
    InvalidRequest,
    Timeout,
    TooManyPending,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PendingRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PendingResponse {
    #[serde(rename = "interactions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub interactions: Vec<PendingInteraction>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PendingInteraction {
    #[serde(rename = "interaction_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub interaction_id: String,
    #[serde(rename = "questions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub questions: Vec<InteractionQuestion>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PendingError {
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct UserInteractionAnswer;
impl RequestCapability for UserInteractionAnswer {
    type Request = AnswerRequest;
    type Response = AnswerResponse;
    type DomainError = AnswerError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ANSWER_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UserInteractionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).answer(context, request)
    }
}

#[derive(Debug)]
pub struct UserInteractionAsk;
impl RequestCapability for UserInteractionAsk {
    type Request = AskRequest;
    type Response = AskResponse;
    type DomainError = AskError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ASK_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UserInteractionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).ask(context, request)
    }
}

#[derive(Debug)]
pub struct UserInteractionPending;
impl RequestCapability for UserInteractionPending {
    type Request = PendingRequest;
    type Response = PendingResponse;
    type DomainError = PendingError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PENDING_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UserInteractionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).pending(context, request)
    }
}

impl serde::Serialize for AnswerError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidAnswer => serializer.serialize_str("invalid_answer"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AnswerError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_answer" => Ok(Self::InvalidAnswer),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for AskError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Timeout => serializer.serialize_str("timeout"),
            Self::TooManyPending => serializer.serialize_str("too_many_pending"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AskError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "timeout" => Ok(Self::Timeout),
                "too_many_pending" => Ok(Self::TooManyPending),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for PendingError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PendingError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_answer_request(value: &AnswerRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_answer_request(wire: &str) -> Result<AnswerRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_answer_response(value: &AnswerResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_answer_response(wire: &str) -> Result<AnswerResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_answer_error(value: &AnswerError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_answer_error(wire: &str) -> Result<AnswerError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_ask_request(value: &AskRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ask_request(wire: &str) -> Result<AskRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ask_response(value: &AskResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ask_response(wire: &str) -> Result<AskResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_ask_error(value: &AskError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_ask_error(wire: &str) -> Result<AskError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_pending_request(value: &PendingRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_pending_request(wire: &str) -> Result<PendingRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_pending_response(value: &PendingResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_pending_response(wire: &str) -> Result<PendingResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_pending_error(value: &PendingError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_pending_error(wire: &str) -> Result<PendingError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoUserInteractionAnswerResult {
    fn __lenso_into_result(self) -> Result<Result<AnswerResponse, AnswerError>, RuntimeFailure>;
}
impl __LensoIntoUserInteractionAnswerResult for Result<AnswerResponse, AnswerError> {
    fn __lenso_into_result(self) -> Result<Result<AnswerResponse, AnswerError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUserInteractionAnswerResult for Result<Result<AnswerResponse, AnswerError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AnswerResponse, AnswerError>, RuntimeFailure> { self }
}
impl __LensoIntoUserInteractionAnswerResult for Result<AnswerResponse, lenso_plugin_authoring::PluginError<AnswerError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AnswerResponse, AnswerError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUserInteractionAnswerResult for Result<AnswerResponse, UserInteractionAnswerInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AnswerResponse, AnswerError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UserInteractionAnswerInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UserInteractionAnswerInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoUserInteractionAskResult {
    fn __lenso_into_result(self) -> Result<Result<AskResponse, AskError>, RuntimeFailure>;
}
impl __LensoIntoUserInteractionAskResult for Result<AskResponse, AskError> {
    fn __lenso_into_result(self) -> Result<Result<AskResponse, AskError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUserInteractionAskResult for Result<Result<AskResponse, AskError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<AskResponse, AskError>, RuntimeFailure> { self }
}
impl __LensoIntoUserInteractionAskResult for Result<AskResponse, lenso_plugin_authoring::PluginError<AskError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<AskResponse, AskError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUserInteractionAskResult for Result<AskResponse, UserInteractionAskInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<AskResponse, AskError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UserInteractionAskInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UserInteractionAskInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoUserInteractionPendingResult {
    fn __lenso_into_result(self) -> Result<Result<PendingResponse, PendingError>, RuntimeFailure>;
}
impl __LensoIntoUserInteractionPendingResult for Result<PendingResponse, PendingError> {
    fn __lenso_into_result(self) -> Result<Result<PendingResponse, PendingError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUserInteractionPendingResult for Result<Result<PendingResponse, PendingError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PendingResponse, PendingError>, RuntimeFailure> { self }
}
impl __LensoIntoUserInteractionPendingResult for Result<PendingResponse, lenso_plugin_authoring::PluginError<PendingError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PendingResponse, PendingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUserInteractionPendingResult for Result<PendingResponse, UserInteractionPendingInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PendingResponse, PendingError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UserInteractionPendingInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UserInteractionPendingInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait UserInteractionProvider: fmt::Debug + 'static {
    fn answer(&self, context: InvocationContext, request: AnswerRequest) -> NativeRequestFuture<UserInteractionAnswer>;
    fn ask(&self, context: InvocationContext, request: AskRequest) -> NativeRequestFuture<UserInteractionAsk>;
    fn pending(&self, context: InvocationContext, request: PendingRequest) -> NativeRequestFuture<UserInteractionPending>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_user_interaction {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportUserInteraction;
        impl $crate::UserInteractionProvider for $plugin {
        fn answer(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AnswerRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAnswer> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::answer(&plugin, context, request).await;
                $crate::__LensoIntoUserInteractionAnswerResult::__lenso_into_result(result)
            })
        }
        fn ask(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AskRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAsk> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::ask(&plugin, context, request).await;
                $crate::__LensoIntoUserInteractionAskResult::__lenso_into_result(result)
            })
        }
        fn pending(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::PendingRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionPending> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::pending(&plugin, context, request).await;
                $crate::__LensoIntoUserInteractionPendingResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_user_interaction {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportUserInteraction;
        impl $crate::UserInteractionProvider for $object {
        fn answer(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AnswerRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAnswer> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::answer(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoUserInteractionAnswerResult::__lenso_into_result(result)
            })
        }
        fn ask(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AskRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAsk> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::ask(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoUserInteractionAskResult::__lenso_into_result(result)
            })
        }
        fn pending(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::PendingRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionPending> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::pending(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoUserInteractionPendingResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_user_interaction {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportUserInteraction;
        impl $crate::UserInteractionProvider for $object {
        fn answer(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AnswerRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAnswer> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::UserInteractionProvider>::answer(plugin.as_ref(), context, request).await
            })
        }
        fn ask(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::AskRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionAsk> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::UserInteractionProvider>::ask(plugin.as_ref(), context, request).await
            })
        }
        fn pending(&self, context: __LensoNativeSupportUserInteraction::InvocationContext, request: $crate::PendingRequest) -> __LensoNativeSupportUserInteraction::NativeRequestFuture<$crate::UserInteractionPending> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::UserInteractionProvider>::pending(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct UserInteractionRequestEndpoint { provider: Rc<dyn UserInteractionProvider> }

#[derive(Debug)]
pub struct UserInteractionEndpoint<P: UserInteractionProvider> { provider: Rc<P>, request_endpoint: UserInteractionRequestEndpoint }
impl<P: UserInteractionProvider> UserInteractionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn UserInteractionProvider> = provider.clone();
        Self { provider, request_endpoint: UserInteractionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: UserInteractionProvider> NativeRequestEndpoint for UserInteractionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        ANSWER_OPERATION,
        ASK_OPERATION,
        PENDING_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            ANSWER_OPERATION => {
                let Ok(request) = request.downcast::<AnswerRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).answer(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            ASK_OPERATION => {
                let Ok(request) = request.downcast::<AskRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).ask(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PENDING_OPERATION => {
                let Ok(request) = request.downcast::<PendingRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).pending(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_user_interaction {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::UserInteractionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_user_interaction {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_user_interaction!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct UserInteractionClient {
    answer: NativeRequestHandle<UserInteractionAnswer>,
    ask: NativeRequestHandle<UserInteractionAsk>,
    pending: NativeRequestHandle<UserInteractionPending>,
}
impl UserInteractionClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn answer(&self, request: AnswerRequest) -> Result<AnswerResponse, UserInteractionAnswerInvocationError> {
        self.answer.invoke(ANSWER_OPERATION, request).await
            .map_err(UserInteractionAnswerInvocationError::Runtime)?
            .map_err(UserInteractionAnswerInvocationError::Domain)
    }

    pub async fn answer_with_context(&self, context: InvocationContext, request: AnswerRequest) -> Result<AnswerResponse, UserInteractionAnswerInvocationError> {
        self.answer.invoke_with_context(ANSWER_OPERATION, context, request).await
            .map_err(UserInteractionAnswerInvocationError::Runtime)?
            .map_err(UserInteractionAnswerInvocationError::Domain)
    }

    pub async fn ask(&self, request: AskRequest) -> Result<AskResponse, UserInteractionAskInvocationError> {
        self.ask.invoke(ASK_OPERATION, request).await
            .map_err(UserInteractionAskInvocationError::Runtime)?
            .map_err(UserInteractionAskInvocationError::Domain)
    }

    pub async fn ask_with_context(&self, context: InvocationContext, request: AskRequest) -> Result<AskResponse, UserInteractionAskInvocationError> {
        self.ask.invoke_with_context(ASK_OPERATION, context, request).await
            .map_err(UserInteractionAskInvocationError::Runtime)?
            .map_err(UserInteractionAskInvocationError::Domain)
    }

    pub async fn pending(&self, request: PendingRequest) -> Result<PendingResponse, UserInteractionPendingInvocationError> {
        self.pending.invoke(PENDING_OPERATION, request).await
            .map_err(UserInteractionPendingInvocationError::Runtime)?
            .map_err(UserInteractionPendingInvocationError::Domain)
    }

    pub async fn pending_with_context(&self, context: InvocationContext, request: PendingRequest) -> Result<PendingResponse, UserInteractionPendingInvocationError> {
        self.pending.invoke_with_context(PENDING_OPERATION, context, request).await
            .map_err(UserInteractionPendingInvocationError::Runtime)?
            .map_err(UserInteractionPendingInvocationError::Domain)
    }
}

impl CapabilityClient for UserInteractionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            answer: dependencies.one::<UserInteractionAnswer>()?,
            ask: dependencies.one::<UserInteractionAsk>()?,
            pending: dependencies.one::<UserInteractionPending>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for UserInteractionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    answer: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UserInteractionAnswer>()?,
                    ask: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UserInteractionAsk>()?,
                    pending: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UserInteractionPending>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum UserInteractionAnswerInvocationError {
    Domain(AnswerError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum UserInteractionAskInvocationError {
    Domain(AskError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum UserInteractionPendingInvocationError {
    Domain(PendingError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct UserInteractionGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> UserInteractionGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[ANSWER_OPERATION, ASK_OPERATION, PENDING_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn answer(&self, request: &AnswerRequest) -> Result<AnswerResponse, lenso_guest_sdk::GuestError<AnswerError>> {
        self.capability.request(ANSWER_OPERATION, request)
    }

    pub fn ask(&self, request: &AskRequest) -> Result<AskResponse, lenso_guest_sdk::GuestError<AskError>> {
        self.capability.request(ASK_OPERATION, request)
    }

    pub fn pending(&self, request: &PendingRequest) -> Result<PendingResponse, lenso_guest_sdk::GuestError<PendingError>> {
        self.capability.request(PENDING_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct UserInteractionJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for UserInteractionJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[ANSWER_OPERATION, ASK_OPERATION, PENDING_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            ANSWER_OPERATION => {
                let value = request.downcast_ref::<AnswerRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            ASK_OPERATION => {
                let value = request.downcast_ref::<AskRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            PENDING_OPERATION => {
                let value = request.downcast_ref::<PendingRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            ANSWER_OPERATION => serde_json::from_value::<AnswerResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            ASK_OPERATION => serde_json::from_value::<AskResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            PENDING_OPERATION => serde_json::from_value::<PendingResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            ANSWER_OPERATION => serde_json::from_value::<AnswerError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            ASK_OPERATION => serde_json::from_value::<AskError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            PENDING_OPERATION => serde_json::from_value::<PendingError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            ANSWER_OPERATION => {
                let request = serde_json::from_value::<AnswerRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<UserInteractionAnswer>()?;
                    match handle.invoke_with_context(ANSWER_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            ASK_OPERATION => {
                let request = serde_json::from_value::<AskRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<UserInteractionAsk>()?;
                    match handle.invoke_with_context(ASK_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            PENDING_OPERATION => {
                let request = serde_json::from_value::<PendingRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<UserInteractionPending>()?;
                    match handle.invoke_with_context(PENDING_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
