// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::CapabilityClient;
pub const CAPABILITY_ID: &str = "lenso.agent.session@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const SESSION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const SESSION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_session { () => { "{\"capability_id\":\"lenso.agent.session@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"append\",\"open\",\"read\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_session_client { () => { "{\"capability_id\":\"lenso.agent.session@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" }; }

pub const APPEND_OPERATION: &str = "append";
pub const OPEN_OPERATION: &str = "open";
pub const READ_OPERATION: &str = "read";

pub use lenso_contract_runtime::{Timestamp, Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendRequest {
    #[serde(rename = "events")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub events: Vec<AppendRequestEventsItem>,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: Uint64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendRequestEventsItem {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: AppendRequestEventsItemKind,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "payload_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload_json: String,
    #[serde(rename = "turn_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum AppendRequestEventsItemKind {
    #[serde(rename = "session_created")]
    SessionCreated,
    #[serde(rename = "turn_started")]
    TurnStarted,
    #[serde(rename = "model_requested")]
    ModelRequested,
    #[serde(rename = "model_output")]
    ModelOutput,
    #[serde(rename = "tool_requested")]
    ToolRequested,
    #[serde(rename = "tool_result")]
    ToolResult,
    #[serde(rename = "turn_completed")]
    TurnCompleted,
    #[serde(rename = "turn_failed")]
    TurnFailed,
    #[serde(rename = "turn_cancelled")]
    TurnCancelled,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendResponse {
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct AppendErrorRevisionConflictPayload {
    #[serde(rename = "current_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub current_revision: Uint64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum AppendError {
    InvalidEvent,
    NotFound,
    RevisionConflict { payload: AppendErrorRevisionConflictPayload },
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OpenRequest {
    #[serde(rename = "session_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct OpenResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum OpenError {
    InvalidSessionId,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadRequest {
    #[serde(rename = "after_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub after_revision: Uint64,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "events")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub events: Vec<ReadResponseEventsItem>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResponseEventsItem {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ReadResponseEventsItemKind,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "payload_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload_json: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: Uint64,
    #[serde(rename = "turn_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadResponseEventsItemKind {
    #[serde(rename = "session_created")]
    SessionCreated,
    #[serde(rename = "turn_started")]
    TurnStarted,
    #[serde(rename = "model_requested")]
    ModelRequested,
    #[serde(rename = "model_output")]
    ModelOutput,
    #[serde(rename = "tool_requested")]
    ToolRequested,
    #[serde(rename = "tool_result")]
    ToolResult,
    #[serde(rename = "turn_completed")]
    TurnCompleted,
    #[serde(rename = "turn_failed")]
    TurnFailed,
    #[serde(rename = "turn_cancelled")]
    TurnCancelled,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadError {
    InvalidCursor,
    NotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct SessionAppend;
impl RequestCapability for SessionAppend {
    type Request = AppendRequest;
    type Response = AppendResponse;
    type DomainError = AppendError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != APPEND_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).append(context, request)
    }
}

#[derive(Debug)]
pub struct SessionOpen;
impl RequestCapability for SessionOpen {
    type Request = OpenRequest;
    type Response = OpenResponse;
    type DomainError = OpenError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != OPEN_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).open(context, request)
    }
}

#[derive(Debug)]
pub struct SessionRead;
impl RequestCapability for SessionRead {
    type Request = ReadRequest;
    type Response = ReadResponse;
    type DomainError = ReadError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<SessionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read(context, request)
    }
}

impl serde::Serialize for AppendError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::RevisionConflict { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "revision_conflict")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for AppendError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_event" => Ok(Self::InvalidEvent),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "revision_conflict" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::RevisionConflict { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for OpenError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidSessionId => serializer.serialize_str("invalid_session_id"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for OpenError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_session_id" => Ok(Self::InvalidSessionId),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidCursor => serializer.serialize_str("invalid_cursor"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_cursor" => Ok(Self::InvalidCursor),
                "not_found" => Ok(Self::NotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_append_request(value: &AppendRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_request(wire: &str) -> Result<AppendRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_response(value: &AppendResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_response(wire: &str) -> Result<AppendResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_append_error(value: &AppendError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_append_error(wire: &str) -> Result<AppendError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_open_request(value: &OpenRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_request(wire: &str) -> Result<OpenRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_open_response(value: &OpenResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_response(wire: &str) -> Result<OpenResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_open_error(value: &OpenError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_open_error(wire: &str) -> Result<OpenError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_request(value: &ReadRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_request(wire: &str) -> Result<ReadRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_response(value: &ReadResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_response(wire: &str) -> Result<ReadResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_error(value: &ReadError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_error(wire: &str) -> Result<ReadError, serde_json::Error> { decode_portable_json(wire) }

pub trait SessionProvider: fmt::Debug + 'static {
    fn append(&self, context: InvocationContext, request: AppendRequest) -> NativeRequestFuture<SessionAppend>;
    fn open(&self, context: InvocationContext, request: OpenRequest) -> NativeRequestFuture<SessionOpen>;
    fn read(&self, context: InvocationContext, request: ReadRequest) -> NativeRequestFuture<SessionRead>;
}

#[derive(Debug)]
struct SessionRequestEndpoint { provider: Rc<dyn SessionProvider> }

#[derive(Debug)]
pub struct SessionEndpoint<P: SessionProvider> { provider: Rc<P>, request_endpoint: SessionRequestEndpoint }
impl<P: SessionProvider> SessionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn SessionProvider> = provider.clone();
        Self { provider, request_endpoint: SessionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: SessionProvider> NativeRequestEndpoint for SessionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        APPEND_OPERATION,
        OPEN_OPERATION,
        READ_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            APPEND_OPERATION => {
                let Ok(request) = request.downcast::<AppendRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).append(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            OPEN_OPERATION => {
                let Ok(request) = request.downcast::<OpenRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).open(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_OPERATION => {
                let Ok(request) = request.downcast::<ReadRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_session {
    ($provider:expr, $lifecycle:expr) => {{
        let endpoint = ::std::rc::Rc::new($crate::SessionEndpoint::new($provider));
        ::lenso_native_adapter::NativeModuleInstance::with_all_endpoints(
            vec![endpoint.clone() as ::std::rc::Rc<dyn ::lenso_kernel::NativeRequestEndpoint>],
            vec![],
            vec![],
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct SessionClient {
    append: NativeRequestHandle<SessionAppend>,
    open: NativeRequestHandle<SessionOpen>,
    read: NativeRequestHandle<SessionRead>,
}
impl SessionClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn append(&self, request: AppendRequest) -> Result<AppendResponse, SessionAppendInvocationError> {
        self.append.invoke(APPEND_OPERATION, request).await
            .map_err(SessionAppendInvocationError::Runtime)?
            .map_err(SessionAppendInvocationError::Domain)
    }

    pub async fn append_with_context(&self, context: InvocationContext, request: AppendRequest) -> Result<AppendResponse, SessionAppendInvocationError> {
        self.append.invoke_with_context(APPEND_OPERATION, context, request).await
            .map_err(SessionAppendInvocationError::Runtime)?
            .map_err(SessionAppendInvocationError::Domain)
    }

    pub async fn open(&self, request: OpenRequest) -> Result<OpenResponse, SessionOpenInvocationError> {
        self.open.invoke(OPEN_OPERATION, request).await
            .map_err(SessionOpenInvocationError::Runtime)?
            .map_err(SessionOpenInvocationError::Domain)
    }

    pub async fn open_with_context(&self, context: InvocationContext, request: OpenRequest) -> Result<OpenResponse, SessionOpenInvocationError> {
        self.open.invoke_with_context(OPEN_OPERATION, context, request).await
            .map_err(SessionOpenInvocationError::Runtime)?
            .map_err(SessionOpenInvocationError::Domain)
    }

    pub async fn read(&self, request: ReadRequest) -> Result<ReadResponse, SessionReadInvocationError> {
        self.read.invoke(READ_OPERATION, request).await
            .map_err(SessionReadInvocationError::Runtime)?
            .map_err(SessionReadInvocationError::Domain)
    }

    pub async fn read_with_context(&self, context: InvocationContext, request: ReadRequest) -> Result<ReadResponse, SessionReadInvocationError> {
        self.read.invoke_with_context(READ_OPERATION, context, request).await
            .map_err(SessionReadInvocationError::Runtime)?
            .map_err(SessionReadInvocationError::Domain)
    }
}

impl CapabilityClient for SessionClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            append: dependencies.one::<SessionAppend>()?,
            open: dependencies.one::<SessionOpen>()?,
            read: dependencies.one::<SessionRead>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SessionAppendInvocationError {
    Domain(AppendError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SessionOpenInvocationError {
    Domain(OpenError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum SessionReadInvocationError {
    Domain(ReadError),
    Runtime(RuntimeFailure),
}
