// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.tool-progress@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:ba88fc5af1eeca647caa9555a8423843a260ee6fe1d548a170c50ddf4e33e21c";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const TOOL_PROGRESS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const TOOL_PROGRESS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const TOOL_PROGRESS_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const TOOL_PROGRESS_CONTRACT: CapabilityReference<ToolProgressClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_tool_progress { () => { "{\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"execute_progress\",\"progress_catalog\"],\"operation_kinds\":{\"execute_progress\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_tool_progress_client {
    () => { "{\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_tool_progress_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_tool_progress_client {
    () => { "{\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.tool-progress@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const EXECUTE_PROGRESS_OPERATION: &str = "execute_progress";
pub const PROGRESS_CATALOG_OPERATION: &str = "progress_catalog";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteOpen {
    #[serde(rename = "arguments_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_json: RawJson,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteProgress {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: ContentType,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ExecuteProgressKind,
    #[serde(rename = "metadata_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata_json: RawJson,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ContentType {
    #[serde(rename = "text")]
    Text,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ExecuteProgressKind {
    #[serde(rename = "stdout")]
    Stdout,
    #[serde(rename = "stderr")]
    Stderr,
    #[serde(rename = "completed")]
    Completed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecutionFailedPayload {
    #[serde(rename = "details_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub details_json: RawJson,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExecuteProgressError {
    ExecutionFailed { payload: ExecutionFailedPayload },
    InvalidArguments,
    NotFound,
    OutputLimitExceeded,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "tools")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tools: Vec<ToolProgressDefinition>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ToolProgressDefinition {
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProgressCatalogError {
    CatalogInvalid,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ToolProgressExecuteProgress;
pub type ToolProgressExecuteProgressEvent = StreamEvent<ExecuteProgress, ExecuteProgressError>;
impl StreamCapability for ToolProgressExecuteProgress {
    type OpenRequest = ExecuteOpen;
    type Message = ExecuteProgress;
    type DomainError = ExecuteProgressError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

#[derive(Debug)]
pub struct ToolProgressProgressCatalog;
impl RequestCapability for ToolProgressProgressCatalog {
    type Request = CatalogRequest;
    type Response = CatalogResponse;
    type DomainError = ProgressCatalogError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PROGRESS_CATALOG_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ToolProgressRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).progress_catalog(context, request)
    }
}

impl serde::Serialize for ExecuteProgressError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExecutionFailed { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "execution_failed")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::InvalidArguments => serializer.serialize_str("invalid_arguments"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OutputLimitExceeded => serializer.serialize_str("output_limit_exceeded"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExecuteProgressError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_arguments" => Ok(Self::InvalidArguments),
                "not_found" => Ok(Self::NotFound),
                "output_limit_exceeded" => Ok(Self::OutputLimitExceeded),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "execution_failed" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ExecutionFailed { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ProgressCatalogError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CatalogInvalid => serializer.serialize_str("catalog_invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ProgressCatalogError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "catalog_invalid" => Ok(Self::CatalogInvalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_execute_progress_request(value: &ExecuteOpen) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_progress_request(wire: &str) -> Result<ExecuteOpen, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_progress_response(value: &ExecuteProgress) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_progress_response(wire: &str) -> Result<ExecuteProgress, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_progress_error(value: &ExecuteProgressError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_progress_error(wire: &str) -> Result<ExecuteProgressError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_progress_catalog_request(value: &CatalogRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_progress_catalog_request(wire: &str) -> Result<CatalogRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_progress_catalog_response(value: &CatalogResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_progress_catalog_response(wire: &str) -> Result<CatalogResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_progress_catalog_error(value: &ProgressCatalogError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_progress_catalog_error(wire: &str) -> Result<ProgressCatalogError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoToolProgressExecuteProgressStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ToolProgressExecuteProgressInvocationError>;
}
impl<S> __LensoIntoToolProgressExecuteProgressStreamResult for Result<S, ExecuteProgressError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ToolProgressExecuteProgressInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(ToolProgressExecuteProgressInvocationError::Domain)
    }
}
impl<S> __LensoIntoToolProgressExecuteProgressStreamResult for Result<S, lenso_plugin_authoring::PluginError<ExecuteProgressError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ToolProgressExecuteProgressInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(ToolProgressExecuteProgressInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(ToolProgressExecuteProgressInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoToolProgressExecuteProgressStreamResult for Result<S, ToolProgressExecuteProgressInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ToolProgressExecuteProgressInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

#[doc(hidden)]
pub trait __LensoIntoToolProgressProgressCatalogResult {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure>;
}
impl __LensoIntoToolProgressProgressCatalogResult for Result<CatalogResponse, ProgressCatalogError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoToolProgressProgressCatalogResult for Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure> { self }
}
impl __LensoIntoToolProgressProgressCatalogResult for Result<CatalogResponse, lenso_plugin_authoring::PluginError<ProgressCatalogError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoToolProgressProgressCatalogResult for Result<CatalogResponse, ToolProgressProgressCatalogInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, ProgressCatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ToolProgressProgressCatalogInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ToolProgressProgressCatalogInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ToolProgressProvider: fmt::Debug + 'static {
    fn execute_progress(&self, context: InvocationContext, request: ExecuteOpen) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ToolProgressExecuteProgressInvocationError>>;
    fn progress_catalog(&self, context: InvocationContext, request: CatalogRequest) -> NativeRequestFuture<ToolProgressProgressCatalog>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_tool_progress {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportToolProgress;
        impl $crate::ToolProgressProvider for $plugin {
        fn execute_progress(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportToolProgress::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportToolProgress::NativeStreamSession>, $crate::ToolProgressExecuteProgressInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::execute_progress(&plugin, context, request).await;
                $crate::__LensoIntoToolProgressExecuteProgressStreamResult::__lenso_into_result(result)
            })
        }
        fn progress_catalog(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportToolProgress::NativeRequestFuture<$crate::ToolProgressProgressCatalog> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::progress_catalog(&plugin, context, request).await;
                $crate::__LensoIntoToolProgressProgressCatalogResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_tool_progress {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportToolProgress;
        impl $crate::ToolProgressProvider for $object {
        fn execute_progress(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportToolProgress::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportToolProgress::NativeStreamSession>, $crate::ToolProgressExecuteProgressInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::ToolProgressExecuteProgressInvocationError::Runtime)?;
                let result = <$plugin>::execute_progress(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoToolProgressExecuteProgressStreamResult::__lenso_into_result(result)
            })
        }
        fn progress_catalog(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportToolProgress::NativeRequestFuture<$crate::ToolProgressProgressCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::progress_catalog(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoToolProgressProgressCatalogResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_tool_progress {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportToolProgress;
        impl $crate::ToolProgressProvider for $object {
        fn execute_progress(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::ExecuteOpen) -> __LensoNativeSupportToolProgress::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportToolProgress::NativeStreamSession>, $crate::ToolProgressExecuteProgressInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::ToolProgressExecuteProgressInvocationError::Runtime)?;
                <$plugin as $crate::ToolProgressProvider>::execute_progress(plugin.as_ref(), context, request).await
            })
        }
        fn progress_catalog(&self, context: __LensoNativeSupportToolProgress::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportToolProgress::NativeRequestFuture<$crate::ToolProgressProgressCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ToolProgressProvider>::progress_catalog(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ToolProgressRequestEndpoint { provider: Rc<dyn ToolProgressProvider> }

#[derive(Debug)]
pub struct ToolProgressEndpoint<P: ToolProgressProvider> { provider: Rc<P>, request_endpoint: ToolProgressRequestEndpoint }
impl<P: ToolProgressProvider> ToolProgressEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ToolProgressProvider> = provider.clone();
        Self { provider, request_endpoint: ToolProgressRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ToolProgressProvider> NativeRequestEndpoint for ToolProgressEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PROGRESS_CATALOG_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PROGRESS_CATALOG_OPERATION => {
                let Ok(request) = request.downcast::<CatalogRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).progress_catalog(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: ToolProgressProvider> NativeStreamEndpoint for ToolProgressEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        EXECUTE_PROGRESS_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            EXECUTE_PROGRESS_OPERATION => {
                let Ok(request) = request.downcast::<ExecuteOpen>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.execute_progress(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ToolProgressExecuteProgressInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ToolProgressExecuteProgressInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_tool_progress {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ToolProgressEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_tool_progress {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_tool_progress!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ToolProgressClient {
    execute_progress: NativeStreamHandle<ToolProgressExecuteProgress>,
    progress_catalog: NativeRequestHandle<ToolProgressProgressCatalog>,
}
impl ToolProgressClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn execute_progress(&self, request: ExecuteOpen) -> Result<NativeStream<ToolProgressExecuteProgress>, ToolProgressExecuteProgressInvocationError> {
        self.execute_progress.open(EXECUTE_PROGRESS_OPERATION, request).await
            .map_err(ToolProgressExecuteProgressInvocationError::Runtime)?
            .map_err(ToolProgressExecuteProgressInvocationError::Domain)
    }

    pub async fn execute_progress_with_context(&self, context: InvocationContext, request: ExecuteOpen) -> Result<NativeStream<ToolProgressExecuteProgress>, ToolProgressExecuteProgressInvocationError> {
        self.execute_progress.open_with_context(EXECUTE_PROGRESS_OPERATION, context, request).await
            .map_err(ToolProgressExecuteProgressInvocationError::Runtime)?
            .map_err(ToolProgressExecuteProgressInvocationError::Domain)
    }

    pub async fn progress_catalog(&self, request: CatalogRequest) -> Result<CatalogResponse, ToolProgressProgressCatalogInvocationError> {
        self.progress_catalog.invoke(PROGRESS_CATALOG_OPERATION, request).await
            .map_err(ToolProgressProgressCatalogInvocationError::Runtime)?
            .map_err(ToolProgressProgressCatalogInvocationError::Domain)
    }

    pub async fn progress_catalog_with_context(&self, context: InvocationContext, request: CatalogRequest) -> Result<CatalogResponse, ToolProgressProgressCatalogInvocationError> {
        self.progress_catalog.invoke_with_context(PROGRESS_CATALOG_OPERATION, context, request).await
            .map_err(ToolProgressProgressCatalogInvocationError::Runtime)?
            .map_err(ToolProgressProgressCatalogInvocationError::Domain)
    }
}

impl CapabilityClient for ToolProgressClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            execute_progress: dependencies.one_stream::<ToolProgressExecuteProgress>()?,
            progress_catalog: dependencies.one::<ToolProgressProgressCatalog>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ToolProgressClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    execute_progress: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ToolProgressExecuteProgress>()?,
                    progress_catalog: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ToolProgressProgressCatalog>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ToolProgressExecuteProgressInvocationError {
    Domain(ExecuteProgressError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ToolProgressProgressCatalogInvocationError {
    Domain(ProgressCatalogError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ToolProgressGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ToolProgressGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[PROGRESS_CATALOG_OPERATION], &[EXECUTE_PROGRESS_OPERATION])
            .map(|capability| Self { capability })
    }

    pub fn execute_progress(&self, request: &ExecuteOpen) -> Result<lenso_guest_sdk::GuestStream<H, ExecuteProgress, ExecuteProgressError>, lenso_guest_sdk::GuestError<ExecuteProgressError>> {
        self.capability.open_stream(EXECUTE_PROGRESS_OPERATION, request)
    }

    pub fn progress_catalog(&self, request: &CatalogRequest) -> Result<CatalogResponse, lenso_guest_sdk::GuestError<ProgressCatalogError>> {
        self.capability.request(PROGRESS_CATALOG_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ToolProgressJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ToolProgressJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[PROGRESS_CATALOG_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[EXECUTE_PROGRESS_OPERATION] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            PROGRESS_CATALOG_OPERATION => {
                let value = request.downcast_ref::<CatalogRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PROGRESS_CATALOG_OPERATION => serde_json::from_value::<CatalogResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PROGRESS_CATALOG_OPERATION => serde_json::from_value::<ProgressCatalogError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            EXECUTE_PROGRESS_OPERATION => {
                let value = request.downcast_ref::<ExecuteOpen>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_message(&self, operation: &str, message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            EXECUTE_PROGRESS_OPERATION => {
                let value = message.downcast_ref::<ExecuteProgress>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_message(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            EXECUTE_PROGRESS_OPERATION => serde_json::from_value::<ExecuteProgress>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            EXECUTE_PROGRESS_OPERATION => serde_json::from_value::<ExecuteProgressError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            PROGRESS_CATALOG_OPERATION => {
                let request = serde_json::from_value::<CatalogRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ToolProgressProgressCatalog>()?;
                    match handle.invoke_with_context(PROGRESS_CATALOG_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        match operation.as_str() {
            EXECUTE_PROGRESS_OPERATION => {
                let request = serde_json::from_value::<ExecuteOpen>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ToolProgressExecuteProgress>()?;
                    match handle.open_with_context(EXECUTE_PROGRESS_OPERATION, context, request).await? {
                        Ok(stream) => Ok(Ok(lenso_runtime_codec::json_host_stream::<ToolProgressExecuteProgress>(
                            stream,
                            |value| serde_json::from_value::<ExecuteProgress>(value).map_err(|_| runtime_codec_protocol_failure()),
                            |message| serde_json::to_value(message).map_err(|_| runtime_codec_protocol_failure()),
                            |error| serde_json::to_value(error).map_err(|_| runtime_codec_protocol_failure()),
                        ))),
                        Err(error) => serde_json::to_value(error)
                            .map(Err)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
