// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.model-selection@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:a1fa9a86bccc39f4d8959e5d2d6edc7b53fdf39dd0f714f2c586406af4922177";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MODEL_SELECTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MODEL_SELECTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const MODEL_SELECTION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const MODEL_SELECTION_CONTRACT: CapabilityReference<ModelSelectionClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_model_selection { () => { "{\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"select\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_model_selection_client {
    () => { "{\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_model_selection_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_model_selection_client {
    () => { "{\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model-selection@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const SELECT_OPERATION: &str = "select";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SelectRequest {
    #[serde(rename = "candidates")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub candidates: Vec<SelectCandidate>,
    #[serde(rename = "input")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input: String,
    #[serde(rename = "policy")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub policy: String,
    #[serde(rename = "selection_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub selection_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SelectCandidate {
    #[serde(rename = "model")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub model: String,
    #[serde(rename = "selected_by_default")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub selected_by_default: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SelectResponse {
    #[serde(rename = "model")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub model: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
    #[serde(rename = "strategy")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub strategy: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SelectError {
    NoCandidate,
    SelectionFailed,
    UnknownPolicy,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ModelSelection;
impl RequestCapability for ModelSelection {
    type Request = SelectRequest;
    type Response = SelectResponse;
    type DomainError = SelectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SELECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ModelSelectionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).select(context, request)
    }
}

impl serde::Serialize for SelectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::NoCandidate => serializer.serialize_str("no_candidate"),
            Self::SelectionFailed => serializer.serialize_str("selection_failed"),
            Self::UnknownPolicy => serializer.serialize_str("unknown_policy"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SelectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "no_candidate" => Ok(Self::NoCandidate),
                "selection_failed" => Ok(Self::SelectionFailed),
                "unknown_policy" => Ok(Self::UnknownPolicy),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_select_request(value: &SelectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_select_request(wire: &str) -> Result<SelectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_select_response(value: &SelectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_select_response(wire: &str) -> Result<SelectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_select_error(value: &SelectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_select_error(wire: &str) -> Result<SelectError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoModelSelectionSelectResult {
    fn __lenso_into_result(self) -> Result<Result<SelectResponse, SelectError>, RuntimeFailure>;
}
impl __LensoIntoModelSelectionSelectResult for Result<SelectResponse, SelectError> {
    fn __lenso_into_result(self) -> Result<Result<SelectResponse, SelectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoModelSelectionSelectResult for Result<Result<SelectResponse, SelectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SelectResponse, SelectError>, RuntimeFailure> { self }
}
impl __LensoIntoModelSelectionSelectResult for Result<SelectResponse, lenso_plugin_authoring::PluginError<SelectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SelectResponse, SelectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoModelSelectionSelectResult for Result<SelectResponse, ModelSelectionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SelectResponse, SelectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ModelSelectionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ModelSelectionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ModelSelectionProvider: fmt::Debug + 'static {
    fn select(&self, context: InvocationContext, request: SelectRequest) -> NativeRequestFuture<ModelSelection>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_model_selection {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModelSelection;
        impl $crate::ModelSelectionProvider for $plugin {
        fn select(&self, context: __LensoNativeSupportModelSelection::InvocationContext, request: $crate::SelectRequest) -> __LensoNativeSupportModelSelection::NativeRequestFuture<$crate::ModelSelection> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::select(&plugin, context, request).await;
                $crate::__LensoIntoModelSelectionSelectResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_model_selection {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModelSelection;
        impl $crate::ModelSelectionProvider for $object {
        fn select(&self, context: __LensoNativeSupportModelSelection::InvocationContext, request: $crate::SelectRequest) -> __LensoNativeSupportModelSelection::NativeRequestFuture<$crate::ModelSelection> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::select(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoModelSelectionSelectResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_model_selection {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModelSelection;
        impl $crate::ModelSelectionProvider for $object {
        fn select(&self, context: __LensoNativeSupportModelSelection::InvocationContext, request: $crate::SelectRequest) -> __LensoNativeSupportModelSelection::NativeRequestFuture<$crate::ModelSelection> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ModelSelectionProvider>::select(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ModelSelectionRequestEndpoint { provider: Rc<dyn ModelSelectionProvider> }

#[derive(Debug)]
pub struct ModelSelectionEndpoint<P: ModelSelectionProvider> { provider: Rc<P>, request_endpoint: ModelSelectionRequestEndpoint }
impl<P: ModelSelectionProvider> ModelSelectionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ModelSelectionProvider> = provider.clone();
        Self { provider, request_endpoint: ModelSelectionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ModelSelectionProvider> NativeRequestEndpoint for ModelSelectionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SELECT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SELECT_OPERATION => {
                let Ok(request) = request.downcast::<SelectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).select(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_model_selection {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ModelSelectionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_model_selection {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_model_selection!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ModelSelectionClient {
    select: NativeRequestHandle<ModelSelection>,
}
impl ModelSelectionClient {
    pub fn new(handle: NativeRequestHandle<ModelSelection>) -> Self {
        Self { select: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn select(&self, request: SelectRequest) -> Result<SelectResponse, ModelSelectionInvocationError> {
        self.select.invoke(SELECT_OPERATION, request).await
            .map_err(ModelSelectionInvocationError::Runtime)?
            .map_err(ModelSelectionInvocationError::Domain)
    }

    pub async fn select_with_context(&self, context: InvocationContext, request: SelectRequest) -> Result<SelectResponse, ModelSelectionInvocationError> {
        self.select.invoke_with_context(SELECT_OPERATION, context, request).await
            .map_err(ModelSelectionInvocationError::Runtime)?
            .map_err(ModelSelectionInvocationError::Domain)
    }
}

impl CapabilityClient for ModelSelectionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            select: dependencies.one::<ModelSelection>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ModelSelectionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    select: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ModelSelection>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ModelSelectionInvocationError {
    Domain(SelectError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ModelSelectionGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ModelSelectionGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[SELECT_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn select(&self, request: &SelectRequest) -> Result<SelectResponse, lenso_guest_sdk::GuestError<SelectError>> {
        self.capability.request(SELECT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ModelSelectionJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ModelSelectionJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[SELECT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SELECT_OPERATION => {
                let value = request.downcast_ref::<SelectRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SELECT_OPERATION => serde_json::from_value::<SelectResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SELECT_OPERATION => serde_json::from_value::<SelectError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            SELECT_OPERATION => {
                let request = serde_json::from_value::<SelectRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ModelSelection>()?;
                    match handle.invoke_with_context(SELECT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
