// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.agent.tui-contribution@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = false;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const TUI_CONTRIBUTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const TUI_CONTRIBUTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_tui_contribution { () => { "{\"capability_id\":\"lenso.agent.tui-contribution@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"snapshot\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_tui_contribution_client { () => { "{\"capability_id\":\"lenso.agent.tui-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_tui_contribution_client { () => { "{\"capability_id\":\"lenso.agent.tui-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const SNAPSHOT_OPERATION: &str = "snapshot";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotResponse {
    #[serde(rename = "panels")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub panels: Vec<SnapshotResponsePanelsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotResponsePanelsItem {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SnapshotError {
    InvalidContribution,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct TuiContribution;
impl RequestCapability for TuiContribution {
    type Request = SnapshotRequest;
    type Response = SnapshotResponse;
    type DomainError = SnapshotError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SNAPSHOT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<TuiContributionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).snapshot(context, request)
    }
}

impl serde::Serialize for SnapshotError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidContribution => serializer.serialize_str("invalid_contribution"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SnapshotError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_contribution" => Ok(Self::InvalidContribution),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_snapshot_request(value: &SnapshotRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_request(wire: &str) -> Result<SnapshotRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_response(value: &SnapshotResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_response(wire: &str) -> Result<SnapshotResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_error(value: &SnapshotError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_error(wire: &str) -> Result<SnapshotError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoTuiContributionSnapshotResult {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure>;
}
impl __LensoIntoTuiContributionSnapshotResult for Result<SnapshotResponse, SnapshotError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoTuiContributionSnapshotResult for Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { self }
}
impl __LensoIntoTuiContributionSnapshotResult for Result<SnapshotResponse, lenso_module_authoring::ModuleError<SnapshotError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoTuiContributionSnapshotResult for Result<SnapshotResponse, TuiContributionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(TuiContributionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(TuiContributionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait TuiContributionProvider: fmt::Debug + 'static {
    fn snapshot(&self, context: InvocationContext, request: SnapshotRequest) -> NativeRequestFuture<TuiContribution>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_tui_contribution {
    ($module:ty, $support:path) => {
        use $support as __LensoNativeSupportTuiContribution;
        impl $crate::TuiContributionProvider for $module {
        fn snapshot(&self, context: __LensoNativeSupportTuiContribution::InvocationContext, request: $crate::SnapshotRequest) -> __LensoNativeSupportTuiContribution::NativeRequestFuture<$crate::TuiContribution> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::snapshot(&module, context, request).await;
                $crate::__LensoIntoTuiContributionSnapshotResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct TuiContributionRequestEndpoint { provider: Rc<dyn TuiContributionProvider> }

#[derive(Debug)]
pub struct TuiContributionEndpoint<P: TuiContributionProvider> { provider: Rc<P>, request_endpoint: TuiContributionRequestEndpoint }
impl<P: TuiContributionProvider> TuiContributionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn TuiContributionProvider> = provider.clone();
        Self { provider, request_endpoint: TuiContributionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: TuiContributionProvider> NativeRequestEndpoint for TuiContributionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SNAPSHOT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SNAPSHOT_OPERATION => {
                let Ok(request) = request.downcast::<SnapshotRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).snapshot(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_tui_contribution {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::TuiContributionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_tui_contribution {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_tui_contribution!($provider, $support);
        __LensoNativeSupport::NativeModuleInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct TuiContributionClient {
    snapshot: NativeRequestHandle<TuiContribution>,
}
impl TuiContributionClient {
    pub fn new(handle: NativeRequestHandle<TuiContribution>) -> Self {
        Self { snapshot: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn snapshot(&self, request: SnapshotRequest) -> Result<SnapshotResponse, TuiContributionInvocationError> {
        self.snapshot.invoke(SNAPSHOT_OPERATION, request).await
            .map_err(TuiContributionInvocationError::Runtime)?
            .map_err(TuiContributionInvocationError::Domain)
    }

    pub async fn snapshot_with_context(&self, context: InvocationContext, request: SnapshotRequest) -> Result<SnapshotResponse, TuiContributionInvocationError> {
        self.snapshot.invoke_with_context(SNAPSHOT_OPERATION, context, request).await
            .map_err(TuiContributionInvocationError::Runtime)?
            .map_err(TuiContributionInvocationError::Domain)
    }
}

impl CapabilityClient for TuiContributionClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            snapshot: dependencies.one::<TuiContribution>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for TuiContributionClient {
    fn many_from_dependencies(
        dependencies: &ModuleDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    snapshot: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<TuiContribution>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum TuiContributionInvocationError {
    Domain(SnapshotError),
    Runtime(RuntimeFailure),
}
