// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.model@4";
pub const DESCRIPTOR_VERSION: &str = "4.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:114add54b20812e84ba4b1c3cd2d4dd829ca96dd15c3ad180d845b6533340eab";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MODEL_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MODEL_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const MODEL_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const MODEL_CONTRACT: CapabilityReference<ModelClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_model { () => { "{\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"operations\":[\"catalog\",\"complete\"],\"operation_kinds\":{\"complete\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_model_client {
    () => { "{\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_model_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_model_client {
    () => { "{\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.model@4\",\"descriptor_version\":\"4.1.0\",\"cardinality\":\"many\"}") };
}

pub const CATALOG_OPERATION: &str = "catalog";
pub const COMPLETE_OPERATION: &str = "complete";

pub use lenso_contract_runtime::{OptionalValue, RawJson, Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "models")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub models: Vec<CatalogModel>,
    #[serde(rename = "provenance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provenance: CatalogProvenance,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogModel {
    #[serde(rename = "compaction_compatibility")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub compaction_compatibility: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "display_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub display_name: String,
    #[serde(rename = "hidden")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub hidden: bool,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "input_modalities")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_modalities: Vec<CatalogInputModality>,
    #[serde(rename = "limits")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limits: CatalogModelLimits,
    #[serde(rename = "parallel_tool_calls")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub parallel_tool_calls: bool,
    #[serde(rename = "reasoning")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reasoning: CatalogControl,
    #[serde(rename = "service_tiers")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_tiers: CatalogControl,
    #[serde(rename = "text_output")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text_output: bool,
    #[serde(rename = "tool_calls")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tool_calls: bool,
    #[serde(rename = "wire_protocol")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub wire_protocol: CatalogWireProtocol,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogInputModality {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "audio")]
    Audio,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogModelLimits {
    #[serde(rename = "context_window_tokens")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub context_window_tokens: OptionalValue<Uint64>,
    #[serde(rename = "max_input_tokens")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub max_input_tokens: OptionalValue<Uint64>,
    #[serde(rename = "max_output_tokens")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub max_output_tokens: OptionalValue<Uint64>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogControl {
    #[serde(rename = "budget_tokens")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub budget_tokens: OptionalValue<CatalogTokenBudget>,
    #[serde(rename = "default")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub default: OptionalValue<String>,
    #[serde(rename = "mode")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub mode: OptionalValue<CatalogControlMode>,
    #[serde(rename = "options")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub options: Vec<CatalogControlOption>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: CatalogControlStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogTokenBudget {
    #[serde(rename = "default")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub default: Uint64,
    #[serde(rename = "maximum")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub maximum: Uint64,
    #[serde(rename = "minimum")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub minimum: Uint64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogControlMode {
    #[serde(rename = "effort")]
    Effort,
    #[serde(rename = "toggle")]
    Toggle,
    #[serde(rename = "budget_tokens")]
    BudgetTokens,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogControlOption {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogControlStatus {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "unsupported")]
    Unsupported,
    #[serde(rename = "selectable")]
    Selectable,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogWireProtocol {
    #[serde(rename = "fixture")]
    Fixture,
    #[serde(rename = "openai_responses")]
    OpenaiResponses,
    #[serde(rename = "openai_chat_completions")]
    OpenaiChatCompletions,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogProvenance {
    #[serde(rename = "fetched_at_unix_seconds")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub fetched_at_unix_seconds: OptionalValue<Uint64>,
    #[serde(rename = "freshness")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub freshness: CatalogFreshness,
    #[serde(rename = "max_stale_seconds")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub max_stale_seconds: OptionalValue<Uint64>,
    #[serde(rename = "revision")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub revision: OptionalValue<String>,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: CatalogSource,
    #[serde(rename = "validated_at_unix_seconds")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub validated_at_unix_seconds: OptionalValue<Uint64>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogFreshness {
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "revalidated")]
    Revalidated,
    #[serde(rename = "stale")]
    Stale,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CatalogSource {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "cache")]
    Cache,
    #[serde(rename = "configured")]
    Configured,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CatalogError {
    CatalogInvalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteOpen {
    #[serde(rename = "continuation_scope")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation_scope: Option<String>,
    #[serde(rename = "max_output_tokens")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_output_tokens: i64,
    #[serde(rename = "messages")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub messages: Vec<CompleteMessageInput>,
    #[serde(rename = "model")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub model: String,
    #[serde(rename = "reasoning_budget_tokens")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_budget_tokens: Option<Uint64>,
    #[serde(rename = "reasoning_effort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(rename = "reasoning_enabled")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_enabled: Option<bool>,
    #[serde(rename = "service_tier")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    #[serde(rename = "temperature")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub temperature: f64,
    #[serde(rename = "tools")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tools: Vec<CompleteTool>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteMessageInput {
    #[serde(rename = "arguments_json")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments_json: Option<RawJson>,
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: CompleteMessageRole,
    #[serde(rename = "tool_call_id")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(rename = "tool_name")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CompleteMessageRole {
    #[serde(rename = "system")]
    System,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "tool")]
    Tool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteTool {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "input_schema_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_schema_json: RawJson,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteMessage {
    #[serde(rename = "arguments_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_json: RawJson,
    #[serde(rename = "input_tokens")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_tokens: Uint64,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: CompleteMessageKind,
    #[serde(rename = "output_tokens")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub output_tokens: Uint64,
    #[serde(rename = "sequence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sequence: Uint64,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
    #[serde(rename = "tool_call_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tool_call_id: String,
    #[serde(rename = "tool_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tool_name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CompleteMessageKind {
    #[serde(rename = "reasoning_summary_delta")]
    ReasoningSummaryDelta,
    #[serde(rename = "text_delta")]
    TextDelta,
    #[serde(rename = "tool_call")]
    ToolCall,
    #[serde(rename = "usage")]
    Usage,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProviderFailurePayload {
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
    #[serde(rename = "retryable")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retryable: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    ContentRejected,
    ContextOverflow,
    InvalidRequest,
    Overloaded,
    ProviderFailure { payload: ProviderFailurePayload },
    RateLimited,
    UnsupportedModel,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ModelCatalog;
impl RequestCapability for ModelCatalog {
    type Request = CatalogRequest;
    type Response = CatalogResponse;
    type DomainError = CatalogError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CATALOG_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ModelRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).catalog(context, request)
    }
}

#[derive(Debug)]
pub struct ModelComplete;
pub type ModelCompleteEvent = StreamEvent<CompleteMessage, CompleteError>;
impl StreamCapability for ModelComplete {
    type OpenRequest = CompleteOpen;
    type Message = CompleteMessage;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for CatalogError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CatalogInvalid => serializer.serialize_str("catalog_invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CatalogError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "catalog_invalid" => Ok(Self::CatalogInvalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContentRejected => serializer.serialize_str("content_rejected"),
            Self::ContextOverflow => serializer.serialize_str("context_overflow"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Overloaded => serializer.serialize_str("overloaded"),
            Self::ProviderFailure { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "provider_failure")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::RateLimited => serializer.serialize_str("rate_limited"),
            Self::UnsupportedModel => serializer.serialize_str("unsupported_model"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "content_rejected" => Ok(Self::ContentRejected),
                "context_overflow" => Ok(Self::ContextOverflow),
                "invalid_request" => Ok(Self::InvalidRequest),
                "overloaded" => Ok(Self::Overloaded),
                "rate_limited" => Ok(Self::RateLimited),
                "unsupported_model" => Ok(Self::UnsupportedModel),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "provider_failure" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ProviderFailure { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_catalog_request(value: &CatalogRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_request(wire: &str) -> Result<CatalogRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_response(value: &CatalogResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_response(wire: &str) -> Result<CatalogResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_error(value: &CatalogError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_error(wire: &str) -> Result<CatalogError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_complete_request(value: &CompleteOpen) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteOpen, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_response(value: &CompleteMessage) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteMessage, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoModelCatalogResult {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure>;
}
impl __LensoIntoModelCatalogResult for Result<CatalogResponse, CatalogError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoModelCatalogResult for Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { self }
}
impl __LensoIntoModelCatalogResult for Result<CatalogResponse, lenso_plugin_authoring::PluginError<CatalogError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoModelCatalogResult for Result<CatalogResponse, ModelCatalogInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ModelCatalogInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ModelCatalogInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoModelCompleteStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelCompleteInvocationError>;
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, CompleteError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelCompleteInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(ModelCompleteInvocationError::Domain)
    }
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, lenso_plugin_authoring::PluginError<CompleteError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelCompleteInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(ModelCompleteInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(ModelCompleteInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoModelCompleteStreamResult for Result<S, ModelCompleteInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, ModelCompleteInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait ModelProvider: fmt::Debug + 'static {
    fn catalog(&self, context: InvocationContext, request: CatalogRequest) -> NativeRequestFuture<ModelCatalog>;
    fn complete(&self, context: InvocationContext, request: CompleteOpen) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, ModelCompleteInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_model {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModel;
        impl $crate::ModelProvider for $plugin {
        fn catalog(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportModel::NativeRequestFuture<$crate::ModelCatalog> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::catalog(&plugin, context, request).await;
                $crate::__LensoIntoModelCatalogResult::__lenso_into_result(result)
            })
        }
        fn complete(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CompleteOpen) -> __LensoNativeSupportModel::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportModel::NativeStreamSession>, $crate::ModelCompleteInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::complete(&plugin, context, request).await;
                $crate::__LensoIntoModelCompleteStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_model {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModel;
        impl $crate::ModelProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportModel::NativeRequestFuture<$crate::ModelCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::catalog(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoModelCatalogResult::__lenso_into_result(result)
            })
        }
        fn complete(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CompleteOpen) -> __LensoNativeSupportModel::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportModel::NativeStreamSession>, $crate::ModelCompleteInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::ModelCompleteInvocationError::Runtime)?;
                let result = <$plugin>::complete(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoModelCompleteStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_model {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportModel;
        impl $crate::ModelProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportModel::NativeRequestFuture<$crate::ModelCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ModelProvider>::catalog(plugin.as_ref(), context, request).await
            })
        }
        fn complete(&self, context: __LensoNativeSupportModel::InvocationContext, request: $crate::CompleteOpen) -> __LensoNativeSupportModel::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportModel::NativeStreamSession>, $crate::ModelCompleteInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::ModelCompleteInvocationError::Runtime)?;
                <$plugin as $crate::ModelProvider>::complete(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ModelRequestEndpoint { provider: Rc<dyn ModelProvider> }

#[derive(Debug)]
pub struct ModelEndpoint<P: ModelProvider> { provider: Rc<P>, request_endpoint: ModelRequestEndpoint }
impl<P: ModelProvider> ModelEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ModelProvider> = provider.clone();
        Self { provider, request_endpoint: ModelRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ModelProvider> NativeRequestEndpoint for ModelEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CATALOG_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CATALOG_OPERATION => {
                let Ok(request) = request.downcast::<CatalogRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).catalog(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: ModelProvider> NativeStreamEndpoint for ModelEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        COMPLETE_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteOpen>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.complete(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(ModelCompleteInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(ModelCompleteInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_model {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ModelEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_model {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_model!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ModelClient {
    catalog: NativeRequestHandle<ModelCatalog>,
    complete: NativeStreamHandle<ModelComplete>,
}
impl ModelClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn catalog(&self, request: CatalogRequest) -> Result<CatalogResponse, ModelCatalogInvocationError> {
        self.catalog.invoke(CATALOG_OPERATION, request).await
            .map_err(ModelCatalogInvocationError::Runtime)?
            .map_err(ModelCatalogInvocationError::Domain)
    }

    pub async fn catalog_with_context(&self, context: InvocationContext, request: CatalogRequest) -> Result<CatalogResponse, ModelCatalogInvocationError> {
        self.catalog.invoke_with_context(CATALOG_OPERATION, context, request).await
            .map_err(ModelCatalogInvocationError::Runtime)?
            .map_err(ModelCatalogInvocationError::Domain)
    }

    pub async fn complete(&self, request: CompleteOpen) -> Result<NativeStream<ModelComplete>, ModelCompleteInvocationError> {
        self.complete.open(COMPLETE_OPERATION, request).await
            .map_err(ModelCompleteInvocationError::Runtime)?
            .map_err(ModelCompleteInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteOpen) -> Result<NativeStream<ModelComplete>, ModelCompleteInvocationError> {
        self.complete.open_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(ModelCompleteInvocationError::Runtime)?
            .map_err(ModelCompleteInvocationError::Domain)
    }
}

impl CapabilityClient for ModelClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            catalog: dependencies.one::<ModelCatalog>()?,
            complete: dependencies.one_stream::<ModelComplete>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ModelClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    catalog: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ModelCatalog>()?,
                    complete: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ModelComplete>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ModelCatalogInvocationError {
    Domain(CatalogError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ModelCompleteInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ModelGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ModelGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[CATALOG_OPERATION], &[COMPLETE_OPERATION])
            .map(|capability| Self { capability })
    }

    pub fn catalog(&self, request: &CatalogRequest) -> Result<CatalogResponse, lenso_guest_sdk::GuestError<CatalogError>> {
        self.capability.request(CATALOG_OPERATION, request)
    }

    pub fn complete(&self, request: &CompleteOpen) -> Result<lenso_guest_sdk::GuestStream<H, CompleteMessage, CompleteError>, lenso_guest_sdk::GuestError<CompleteError>> {
        self.capability.open_stream(COMPLETE_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ModelJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ModelJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[CATALOG_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[COMPLETE_OPERATION] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => {
                let value = request.downcast_ref::<CatalogRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            COMPLETE_OPERATION => {
                let value = request.downcast_ref::<CompleteOpen>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_message(&self, operation: &str, message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            COMPLETE_OPERATION => {
                let value = message.downcast_ref::<CompleteMessage>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_message(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            COMPLETE_OPERATION => serde_json::from_value::<CompleteMessage>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            COMPLETE_OPERATION => serde_json::from_value::<CompleteError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            CATALOG_OPERATION => {
                let request = serde_json::from_value::<CatalogRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ModelCatalog>()?;
                    match handle.invoke_with_context(CATALOG_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        match operation.as_str() {
            COMPLETE_OPERATION => {
                let request = serde_json::from_value::<CompleteOpen>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ModelComplete>()?;
                    match handle.open_with_context(COMPLETE_OPERATION, context, request).await? {
                        Ok(stream) => Ok(Ok(lenso_runtime_codec::json_host_stream::<ModelComplete>(
                            stream,
                            |value| serde_json::from_value::<CompleteMessage>(value).map_err(|_| runtime_codec_protocol_failure()),
                            |message| serde_json::to_value(message).map_err(|_| runtime_codec_protocol_failure()),
                            |error| serde_json::to_value(error).map_err(|_| runtime_codec_protocol_failure()),
                        ))),
                        Err(error) => serde_json::to_value(error)
                            .map(Err)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
