// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::CapabilityClient;
pub const CAPABILITY_ID: &str = "lenso.agent.tool-provider@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const TOOL_PROVIDER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const TOOL_PROVIDER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_tool_provider { () => { "{\"capability_id\":\"lenso.agent.tool-provider@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"catalog\",\"execute\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_tool_provider_client { () => { "{\"capability_id\":\"lenso.agent.tool-provider@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

pub const CATALOG_OPERATION: &str = "catalog";
pub const EXECUTE_OPERATION: &str = "execute";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "tools")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub tools: Vec<CatalogResponseToolsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponseToolsItem {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "input_schema_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_schema_json: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CatalogError {
    CatalogInvalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteRequest {
    #[serde(rename = "arguments_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_json: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteResponse {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: ExecuteResponseContentType,
    #[serde(rename = "metadata_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata_json: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ExecuteResponseContentType {
    #[serde(rename = "text")]
    Text,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ExecuteErrorExecutionFailedPayload {
    #[serde(rename = "details_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub details_json: String,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ExecuteError {
    ExecutionFailed { payload: ExecuteErrorExecutionFailedPayload },
    InvalidArguments,
    NotFound,
    OutputLimitExceeded,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ToolProviderCatalog;
impl RequestCapability for ToolProviderCatalog {
    type Request = CatalogRequest;
    type Response = CatalogResponse;
    type DomainError = CatalogError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CATALOG_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ToolProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).catalog(context, request)
    }
}

#[derive(Debug)]
pub struct ToolProviderExecute;
impl RequestCapability for ToolProviderExecute {
    type Request = ExecuteRequest;
    type Response = ExecuteResponse;
    type DomainError = ExecuteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != EXECUTE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ToolProviderRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).execute(context, request)
    }
}

impl serde::Serialize for CatalogError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CatalogInvalid => serializer.serialize_str("catalog_invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CatalogError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "catalog_invalid" => Ok(Self::CatalogInvalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ExecuteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExecutionFailed { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "execution_failed")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::InvalidArguments => serializer.serialize_str("invalid_arguments"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OutputLimitExceeded => serializer.serialize_str("output_limit_exceeded"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ExecuteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_arguments" => Ok(Self::InvalidArguments),
                "not_found" => Ok(Self::NotFound),
                "output_limit_exceeded" => Ok(Self::OutputLimitExceeded),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "execution_failed" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ExecutionFailed { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_catalog_request(value: &CatalogRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_request(wire: &str) -> Result<CatalogRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_response(value: &CatalogResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_response(wire: &str) -> Result<CatalogResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_error(value: &CatalogError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_error(wire: &str) -> Result<CatalogError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_execute_request(value: &ExecuteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_request(wire: &str) -> Result<ExecuteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_response(value: &ExecuteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_response(wire: &str) -> Result<ExecuteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_execute_error(value: &ExecuteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_execute_error(wire: &str) -> Result<ExecuteError, serde_json::Error> { decode_portable_json(wire) }

pub trait ToolProviderProvider: fmt::Debug + 'static {
    fn catalog(&self, context: InvocationContext, request: CatalogRequest) -> NativeRequestFuture<ToolProviderCatalog>;
    fn execute(&self, context: InvocationContext, request: ExecuteRequest) -> NativeRequestFuture<ToolProviderExecute>;
}

#[derive(Debug)]
struct ToolProviderRequestEndpoint { provider: Rc<dyn ToolProviderProvider> }

#[derive(Debug)]
pub struct ToolProviderEndpoint<P: ToolProviderProvider> { provider: Rc<P>, request_endpoint: ToolProviderRequestEndpoint }
impl<P: ToolProviderProvider> ToolProviderEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ToolProviderProvider> = provider.clone();
        Self { provider, request_endpoint: ToolProviderRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ToolProviderProvider> NativeRequestEndpoint for ToolProviderEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CATALOG_OPERATION,
        EXECUTE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CATALOG_OPERATION => {
                let Ok(request) = request.downcast::<CatalogRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).catalog(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            EXECUTE_OPERATION => {
                let Ok(request) = request.downcast::<ExecuteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).execute(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_tool_provider {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ToolProviderEndpoint::new($provider));
        __LensoNativeSupport::NativeModuleInstance::with_all_endpoints(
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ToolProviderClient {
    catalog: NativeRequestHandle<ToolProviderCatalog>,
    execute: NativeRequestHandle<ToolProviderExecute>,
}
impl ToolProviderClient {
    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn catalog(&self, request: CatalogRequest) -> Result<CatalogResponse, ToolProviderCatalogInvocationError> {
        self.catalog.invoke(CATALOG_OPERATION, request).await
            .map_err(ToolProviderCatalogInvocationError::Runtime)?
            .map_err(ToolProviderCatalogInvocationError::Domain)
    }

    pub async fn catalog_with_context(&self, context: InvocationContext, request: CatalogRequest) -> Result<CatalogResponse, ToolProviderCatalogInvocationError> {
        self.catalog.invoke_with_context(CATALOG_OPERATION, context, request).await
            .map_err(ToolProviderCatalogInvocationError::Runtime)?
            .map_err(ToolProviderCatalogInvocationError::Domain)
    }

    pub async fn execute(&self, request: ExecuteRequest) -> Result<ExecuteResponse, ToolProviderExecuteInvocationError> {
        self.execute.invoke(EXECUTE_OPERATION, request).await
            .map_err(ToolProviderExecuteInvocationError::Runtime)?
            .map_err(ToolProviderExecuteInvocationError::Domain)
    }

    pub async fn execute_with_context(&self, context: InvocationContext, request: ExecuteRequest) -> Result<ExecuteResponse, ToolProviderExecuteInvocationError> {
        self.execute.invoke_with_context(EXECUTE_OPERATION, context, request).await
            .map_err(ToolProviderExecuteInvocationError::Runtime)?
            .map_err(ToolProviderExecuteInvocationError::Domain)
    }
}

impl CapabilityClient for ToolProviderClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            catalog: dependencies.one::<ToolProviderCatalog>()?,
            execute: dependencies.one::<ToolProviderExecute>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ToolProviderCatalogInvocationError {
    Domain(CatalogError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ToolProviderExecuteInvocationError {
    Domain(ExecuteError),
    Runtime(RuntimeFailure),
}
