// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.turn-input@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:f569d95ca4ef25c01c138ffe5e17a4a5a21a5e4d52ae5cc74396009ee1352413";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const TURN_INPUT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const TURN_INPUT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const TURN_INPUT_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const TURN_INPUT_CONTRACT: CapabilityReference<TurnInputClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_turn_input { () => { "{\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"submit\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_turn_input_client {
    () => { "{\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_turn_input_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_turn_input_client {
    () => { "{\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.turn-input@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const SUBMIT_OPERATION: &str = "submit";

pub use lenso_contract_runtime::{Uint64, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SubmitRequest {
    #[serde(rename = "input")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input: String,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SubmitResponse {
    #[serde(rename = "accepted_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_revision: Uint64,
    #[serde(rename = "session_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub session_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SubmitError {
    InputClosed,
    InvalidInput,
    TurnNotActive,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct TurnInput;
impl RequestCapability for TurnInput {
    type Request = SubmitRequest;
    type Response = SubmitResponse;
    type DomainError = SubmitError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SUBMIT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<TurnInputRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).submit(context, request)
    }
}

impl serde::Serialize for SubmitError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InputClosed => serializer.serialize_str("input_closed"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::TurnNotActive => serializer.serialize_str("turn_not_active"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SubmitError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "input_closed" => Ok(Self::InputClosed),
                "invalid_input" => Ok(Self::InvalidInput),
                "turn_not_active" => Ok(Self::TurnNotActive),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_submit_request(value: &SubmitRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_submit_request(wire: &str) -> Result<SubmitRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_submit_response(value: &SubmitResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_submit_response(wire: &str) -> Result<SubmitResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_submit_error(value: &SubmitError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_submit_error(wire: &str) -> Result<SubmitError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoTurnInputSubmitResult {
    fn __lenso_into_result(self) -> Result<Result<SubmitResponse, SubmitError>, RuntimeFailure>;
}
impl __LensoIntoTurnInputSubmitResult for Result<SubmitResponse, SubmitError> {
    fn __lenso_into_result(self) -> Result<Result<SubmitResponse, SubmitError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoTurnInputSubmitResult for Result<Result<SubmitResponse, SubmitError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SubmitResponse, SubmitError>, RuntimeFailure> { self }
}
impl __LensoIntoTurnInputSubmitResult for Result<SubmitResponse, lenso_plugin_authoring::PluginError<SubmitError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SubmitResponse, SubmitError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoTurnInputSubmitResult for Result<SubmitResponse, TurnInputInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SubmitResponse, SubmitError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(TurnInputInvocationError::Domain(error)) => Ok(Err(error)),
            Err(TurnInputInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait TurnInputProvider: fmt::Debug + 'static {
    fn submit(&self, context: InvocationContext, request: SubmitRequest) -> NativeRequestFuture<TurnInput>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_turn_input {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportTurnInput;
        impl $crate::TurnInputProvider for $plugin {
        fn submit(&self, context: __LensoNativeSupportTurnInput::InvocationContext, request: $crate::SubmitRequest) -> __LensoNativeSupportTurnInput::NativeRequestFuture<$crate::TurnInput> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::submit(&plugin, context, request).await;
                $crate::__LensoIntoTurnInputSubmitResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_turn_input {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportTurnInput;
        impl $crate::TurnInputProvider for $object {
        fn submit(&self, context: __LensoNativeSupportTurnInput::InvocationContext, request: $crate::SubmitRequest) -> __LensoNativeSupportTurnInput::NativeRequestFuture<$crate::TurnInput> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::submit(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoTurnInputSubmitResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_turn_input {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportTurnInput;
        impl $crate::TurnInputProvider for $object {
        fn submit(&self, context: __LensoNativeSupportTurnInput::InvocationContext, request: $crate::SubmitRequest) -> __LensoNativeSupportTurnInput::NativeRequestFuture<$crate::TurnInput> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::TurnInputProvider>::submit(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct TurnInputRequestEndpoint { provider: Rc<dyn TurnInputProvider> }

#[derive(Debug)]
pub struct TurnInputEndpoint<P: TurnInputProvider> { provider: Rc<P>, request_endpoint: TurnInputRequestEndpoint }
impl<P: TurnInputProvider> TurnInputEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn TurnInputProvider> = provider.clone();
        Self { provider, request_endpoint: TurnInputRequestEndpoint { provider: request_provider } }
    }
}

impl<P: TurnInputProvider> NativeRequestEndpoint for TurnInputEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SUBMIT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SUBMIT_OPERATION => {
                let Ok(request) = request.downcast::<SubmitRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).submit(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_turn_input {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::TurnInputEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_turn_input {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_turn_input!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct TurnInputClient {
    submit: NativeRequestHandle<TurnInput>,
}
impl TurnInputClient {
    pub fn new(handle: NativeRequestHandle<TurnInput>) -> Self {
        Self { submit: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn submit(&self, request: SubmitRequest) -> Result<SubmitResponse, TurnInputInvocationError> {
        self.submit.invoke(SUBMIT_OPERATION, request).await
            .map_err(TurnInputInvocationError::Runtime)?
            .map_err(TurnInputInvocationError::Domain)
    }

    pub async fn submit_with_context(&self, context: InvocationContext, request: SubmitRequest) -> Result<SubmitResponse, TurnInputInvocationError> {
        self.submit.invoke_with_context(SUBMIT_OPERATION, context, request).await
            .map_err(TurnInputInvocationError::Runtime)?
            .map_err(TurnInputInvocationError::Domain)
    }
}

impl CapabilityClient for TurnInputClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            submit: dependencies.one::<TurnInput>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for TurnInputClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    submit: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<TurnInput>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum TurnInputInvocationError {
    Domain(SubmitError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct TurnInputGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> TurnInputGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[SUBMIT_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn submit(&self, request: &SubmitRequest) -> Result<SubmitResponse, lenso_guest_sdk::GuestError<SubmitError>> {
        self.capability.request(SUBMIT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct TurnInputJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for TurnInputJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[SUBMIT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SUBMIT_OPERATION => {
                let value = request.downcast_ref::<SubmitRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SUBMIT_OPERATION => serde_json::from_value::<SubmitResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SUBMIT_OPERATION => serde_json::from_value::<SubmitError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            SUBMIT_OPERATION => {
                let request = serde_json::from_value::<SubmitRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<TurnInput>()?;
                    match handle.invoke_with_context(SUBMIT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
