// Generated by `lenso plugin new`. Do not edit.
use lenso_process_sdk::{ProcessOutcome, ProcessPlugin};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

const CAPABILITY: &str = "lenso.agent.tool-provider@2";
const TOOL: &str = "uppercase";

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ExecuteRequest {
    name: String,
    arguments_json: String,
}

#[derive(Serialize)]
struct ExecuteResponse {
    content_type: &'static str,
    content: String,
    metadata_json: &'static str,
}

#[derive(Debug)]
struct GeneratedPlugin;

impl GeneratedPlugin {
    fn catalog() -> ProcessOutcome {
        let schema = schemars::schema_for!(crate::plugin::Arguments);
        let input_schema_json = match serde_json::to_string(&schema) {
            Ok(schema) => schema,
            Err(error) => return ProcessOutcome::Failure(error.to_string()),
        };
        ProcessOutcome::Success(json!({
            "tools": [{
                "name": TOOL,
                "description": "Convert one UTF-8 string to uppercase.",
                "input_schema_json": input_schema_json,
                "execution": "parallel_safe",
            }],
        }))
    }
}

impl ProcessPlugin for GeneratedPlugin {
    fn descriptor(&self) -> Value {
        serde_json::from_str(include_str!("../lenso.generated.descriptor.json"))
            .expect("generated descriptor is valid JSON")
    }

    fn invoke(&self, capability: &str, operation: &str, request: Value) -> ProcessOutcome {
        if capability != CAPABILITY {
            return ProcessOutcome::DomainError(json!("not_found"));
        }
        match operation {
            "catalog" => Self::catalog(),
            "execute" => {
                let request = match serde_json::from_value::<ExecuteRequest>(request) {
                    Ok(request) => request,
                    Err(_) => return ProcessOutcome::DomainError(json!("invalid_arguments")),
                };
                if request.name != TOOL {
                    return ProcessOutcome::DomainError(json!("not_found"));
                }
                let arguments =
                    match serde_json::from_str::<crate::plugin::Arguments>(&request.arguments_json) {
                        Ok(arguments) => arguments,
                        Err(_) => {
                            return ProcessOutcome::DomainError(json!("invalid_arguments"));
                        }
                    };
                match crate::plugin::execute(arguments) {
                    Ok(content) => match serde_json::to_value(ExecuteResponse {
                        content_type: "text",
                        content,
                        metadata_json: r#"{"provider":"external-process"}"#,
                    }) {
                        Ok(value) => ProcessOutcome::Success(value),
                        Err(error) => ProcessOutcome::Failure(error.to_string()),
                    },
                    Err(error) => ProcessOutcome::DomainError(
                        serde_json::to_value(error).unwrap_or_else(|_| json!("execution_failed")),
                    ),
                }
            }
            _ => ProcessOutcome::DomainError(json!("not_found")),
        }
    }
}

fn main() {
    lenso_process_sdk::serve(&GeneratedPlugin).expect("serve Lenso Process Plugin");
}
