// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, ModuleDependencies, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, RequestCapability, RuntimeFailure};

use lenso_module_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.agent.http-fetch@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const HTTP_FETCH_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const HTTP_FETCH_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_http_fetch { () => { "{\"capability_id\":\"lenso.agent.http-fetch@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"get\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_http_fetch_client { () => { "{\"capability_id\":\"lenso.agent.http-fetch@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_http_fetch_client { () => { "{\"capability_id\":\"lenso.agent.http-fetch@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const GET_OPERATION: &str = "get";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequest {
    #[serde(rename = "url")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub url: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetResponse {
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "content_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_type: String,
    #[serde(rename = "metadata_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata_json: RawJson,
    #[serde(rename = "status_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_code: i64,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetErrorExecutionFailedPayload {
    #[serde(rename = "details_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub details_json: RawJson,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetError {
    ExecutionFailed { payload: GetErrorExecutionFailedPayload },
    InvalidUrl,
    OutputLimitExceeded,
    PermissionDenied,
    ResponseNotUtf8,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct HttpFetch;
impl RequestCapability for HttpFetch {
    type Request = GetRequest;
    type Response = GetResponse;
    type DomainError = GetError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<HttpFetchRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get(context, request)
    }
}

impl serde::Serialize for GetError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExecutionFailed { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "execution_failed")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::InvalidUrl => serializer.serialize_str("invalid_url"),
            Self::OutputLimitExceeded => serializer.serialize_str("output_limit_exceeded"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::ResponseNotUtf8 => serializer.serialize_str("response_not_utf8"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_url" => Ok(Self::InvalidUrl),
                "output_limit_exceeded" => Ok(Self::OutputLimitExceeded),
                "permission_denied" => Ok(Self::PermissionDenied),
                "response_not_utf8" => Ok(Self::ResponseNotUtf8),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "execution_failed" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ExecutionFailed { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_get_request(value: &GetRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request(wire: &str) -> Result<GetRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_response(value: &GetResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_response(wire: &str) -> Result<GetResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_error(value: &GetError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_error(wire: &str) -> Result<GetError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoHttpFetchGetResult {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure>;
}
impl __LensoIntoHttpFetchGetResult for Result<GetResponse, GetError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoHttpFetchGetResult for Result<Result<GetResponse, GetError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> { self }
}
impl __LensoIntoHttpFetchGetResult for Result<GetResponse, lenso_module_authoring::ModuleError<GetError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_module_authoring::ModuleError::Domain(error)) => Ok(Err(error)),
            Err(lenso_module_authoring::ModuleError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoHttpFetchGetResult for Result<GetResponse, HttpFetchInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetResponse, GetError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(HttpFetchInvocationError::Domain(error)) => Ok(Err(error)),
            Err(HttpFetchInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait HttpFetchProvider: fmt::Debug + 'static {
    fn get(&self, context: InvocationContext, request: GetRequest) -> NativeRequestFuture<HttpFetch>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_http_fetch {
    ($module:ty, $support:path) => {
        use $support as __LensoNativeSupportHttpFetch;
        impl $crate::HttpFetchProvider for $module {
        fn get(&self, context: __LensoNativeSupportHttpFetch::InvocationContext, request: $crate::GetRequest) -> __LensoNativeSupportHttpFetch::NativeRequestFuture<$crate::HttpFetch> {
            let module = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$module>::get(&module, context, request).await;
                $crate::__LensoIntoHttpFetchGetResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct HttpFetchRequestEndpoint { provider: Rc<dyn HttpFetchProvider> }

#[derive(Debug)]
pub struct HttpFetchEndpoint<P: HttpFetchProvider> { provider: Rc<P>, request_endpoint: HttpFetchRequestEndpoint }
impl<P: HttpFetchProvider> HttpFetchEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn HttpFetchProvider> = provider.clone();
        Self { provider, request_endpoint: HttpFetchRequestEndpoint { provider: request_provider } }
    }
}

impl<P: HttpFetchProvider> NativeRequestEndpoint for HttpFetchEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        GET_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            GET_OPERATION => {
                let Ok(request) = request.downcast::<GetRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_http_fetch {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::HttpFetchEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_http_fetch {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_http_fetch!($provider, $support);
        __LensoNativeSupport::NativeModuleInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct HttpFetchClient {
    get: NativeRequestHandle<HttpFetch>,
}
impl HttpFetchClient {
    pub fn new(handle: NativeRequestHandle<HttpFetch>) -> Self {
        Self { get: handle }
    }

    pub fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn get(&self, request: GetRequest) -> Result<GetResponse, HttpFetchInvocationError> {
        self.get.invoke(GET_OPERATION, request).await
            .map_err(HttpFetchInvocationError::Runtime)?
            .map_err(HttpFetchInvocationError::Domain)
    }

    pub async fn get_with_context(&self, context: InvocationContext, request: GetRequest) -> Result<GetResponse, HttpFetchInvocationError> {
        self.get.invoke_with_context(GET_OPERATION, context, request).await
            .map_err(HttpFetchInvocationError::Runtime)?
            .map_err(HttpFetchInvocationError::Domain)
    }
}

impl CapabilityClient for HttpFetchClient {
    type Dependencies = ModuleDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &ModuleDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            get: dependencies.one::<HttpFetch>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::ModuleFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for HttpFetchClient {
    fn many_from_dependencies(
        dependencies: &ModuleDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    get: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<HttpFetch>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum HttpFetchInvocationError {
    Domain(GetError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct HttpFetchGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> HttpFetchGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[GET_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn get(&self, request: &GetRequest) -> Result<GetResponse, lenso_guest_sdk::GuestError<GetError>> {
        self.capability.request(GET_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct HttpFetchJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for HttpFetchJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn request_operations(&self) -> &'static [&'static str] { &[GET_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            GET_OPERATION => {
                let value = request.downcast_ref::<GetRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            GET_OPERATION => serde_json::from_value::<GetResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            GET_OPERATION => serde_json::from_value::<GetError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::ModuleDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            GET_OPERATION => {
                let request = serde_json::from_value::<GetRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<HttpFetch>()?;
                    match handle.invoke_with_context(GET_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::ModuleStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
