// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.agent.context-source@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:3d7e1ce9df7fa0457d0abf8ac80ab5cc0f3656047fea593b3ec6402553790ad4";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const CONTEXT_SOURCE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CONTEXT_SOURCE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const CONTEXT_SOURCE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const CONTEXT_SOURCE_CONTRACT: CapabilityReference<ContextSourceClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_context_source { () => { "{\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"read_resource\",\"render_prompt\",\"snapshot\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_context_source_client {
    () => { "{\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_context_source_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_context_source_client {
    () => { "{\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.agent.context-source@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const READ_RESOURCE_OPERATION: &str = "read_resource";
pub const RENDER_PROMPT_OPERATION: &str = "render_prompt";
pub const SNAPSHOT_OPERATION: &str = "snapshot";

pub use lenso_contract_runtime::{OptionalValue, RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResourceRequest {
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
    #[serde(rename = "uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub uri: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadResourceResponse {
    #[serde(rename = "contents")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub contents: Vec<ResourceContent>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResourceContent {
    #[serde(rename = "data_base64")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub data_base64: OptionalValue<String>,
    #[serde(rename = "mime_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mime_type: String,
    #[serde(rename = "text")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub text: OptionalValue<String>,
    #[serde(rename = "uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub uri: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadResourceError {
    InvalidRequest,
    NotFound,
    UnsupportedContent,
    UpstreamFailed,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderPromptRequest {
    #[serde(rename = "arguments_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_json: RawJson,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenderPromptResponse {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "messages")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub messages: Vec<ContextMessage>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ContextMessage {
    #[serde(rename = "role")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub role: ContextRole,
    #[serde(rename = "text")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub text: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ContextRole {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenderPromptError {
    InvalidRequest,
    NotFound,
    UnsupportedContent,
    UpstreamFailed,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SnapshotResponse {
    #[serde(rename = "prompts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub prompts: Vec<PromptDefinition>,
    #[serde(rename = "resources")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub resources: Vec<ResourceDefinition>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PromptDefinition {
    #[serde(rename = "arguments_schema_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub arguments_schema_json: RawJson,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ResourceDefinition {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "mime_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub mime_type: String,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: String,
    #[serde(rename = "uri")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub uri: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SnapshotError {
    InvalidRequest,
    NotFound,
    UnsupportedContent,
    UpstreamFailed,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ContextSourceReadResource;
impl RequestCapability for ContextSourceReadResource {
    type Request = ReadResourceRequest;
    type Response = ReadResourceResponse;
    type DomainError = ReadResourceError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_RESOURCE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContextSourceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_resource(context, request)
    }
}

#[derive(Debug)]
pub struct ContextSourceRenderPrompt;
impl RequestCapability for ContextSourceRenderPrompt {
    type Request = RenderPromptRequest;
    type Response = RenderPromptResponse;
    type DomainError = RenderPromptError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RENDER_PROMPT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContextSourceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).render_prompt(context, request)
    }
}

#[derive(Debug)]
pub struct ContextSourceSnapshot;
impl RequestCapability for ContextSourceSnapshot {
    type Request = SnapshotRequest;
    type Response = SnapshotResponse;
    type DomainError = SnapshotError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SNAPSHOT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContextSourceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).snapshot(context, request)
    }
}

impl serde::Serialize for ReadResourceError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::UnsupportedContent => serializer.serialize_str("unsupported_content"),
            Self::UpstreamFailed => serializer.serialize_str("upstream_failed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadResourceError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "unsupported_content" => Ok(Self::UnsupportedContent),
                "upstream_failed" => Ok(Self::UpstreamFailed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenderPromptError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::UnsupportedContent => serializer.serialize_str("unsupported_content"),
            Self::UpstreamFailed => serializer.serialize_str("upstream_failed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenderPromptError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "unsupported_content" => Ok(Self::UnsupportedContent),
                "upstream_failed" => Ok(Self::UpstreamFailed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SnapshotError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::UnsupportedContent => serializer.serialize_str("unsupported_content"),
            Self::UpstreamFailed => serializer.serialize_str("upstream_failed"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SnapshotError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "not_found" => Ok(Self::NotFound),
                "unsupported_content" => Ok(Self::UnsupportedContent),
                "upstream_failed" => Ok(Self::UpstreamFailed),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_resource_request(value: &ReadResourceRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_resource_request(wire: &str) -> Result<ReadResourceRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_resource_response(value: &ReadResourceResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_resource_response(wire: &str) -> Result<ReadResourceResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_resource_error(value: &ReadResourceError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_resource_error(wire: &str) -> Result<ReadResourceError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_render_prompt_request(value: &RenderPromptRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_prompt_request(wire: &str) -> Result<RenderPromptRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_prompt_response(value: &RenderPromptResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_prompt_response(wire: &str) -> Result<RenderPromptResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_render_prompt_error(value: &RenderPromptError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_render_prompt_error(wire: &str) -> Result<RenderPromptError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_snapshot_request(value: &SnapshotRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_request(wire: &str) -> Result<SnapshotRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_response(value: &SnapshotResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_response(wire: &str) -> Result<SnapshotResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_snapshot_error(value: &SnapshotError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_snapshot_error(wire: &str) -> Result<SnapshotError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoContextSourceReadResourceResult {
    fn __lenso_into_result(self) -> Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure>;
}
impl __LensoIntoContextSourceReadResourceResult for Result<ReadResourceResponse, ReadResourceError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContextSourceReadResourceResult for Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure> { self }
}
impl __LensoIntoContextSourceReadResourceResult for Result<ReadResourceResponse, lenso_plugin_authoring::PluginError<ReadResourceError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContextSourceReadResourceResult for Result<ReadResourceResponse, ContextSourceReadResourceInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadResourceResponse, ReadResourceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContextSourceReadResourceInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContextSourceReadResourceInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContextSourceRenderPromptResult {
    fn __lenso_into_result(self) -> Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure>;
}
impl __LensoIntoContextSourceRenderPromptResult for Result<RenderPromptResponse, RenderPromptError> {
    fn __lenso_into_result(self) -> Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContextSourceRenderPromptResult for Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure> { self }
}
impl __LensoIntoContextSourceRenderPromptResult for Result<RenderPromptResponse, lenso_plugin_authoring::PluginError<RenderPromptError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContextSourceRenderPromptResult for Result<RenderPromptResponse, ContextSourceRenderPromptInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RenderPromptResponse, RenderPromptError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContextSourceRenderPromptInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContextSourceRenderPromptInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoContextSourceSnapshotResult {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure>;
}
impl __LensoIntoContextSourceSnapshotResult for Result<SnapshotResponse, SnapshotError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContextSourceSnapshotResult for Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> { self }
}
impl __LensoIntoContextSourceSnapshotResult for Result<SnapshotResponse, lenso_plugin_authoring::PluginError<SnapshotError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContextSourceSnapshotResult for Result<SnapshotResponse, ContextSourceSnapshotInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SnapshotResponse, SnapshotError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContextSourceSnapshotInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContextSourceSnapshotInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ContextSourceProvider: fmt::Debug + 'static {
    fn read_resource(&self, context: InvocationContext, request: ReadResourceRequest) -> NativeRequestFuture<ContextSourceReadResource>;
    fn render_prompt(&self, context: InvocationContext, request: RenderPromptRequest) -> NativeRequestFuture<ContextSourceRenderPrompt>;
    fn snapshot(&self, context: InvocationContext, request: SnapshotRequest) -> NativeRequestFuture<ContextSourceSnapshot>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_context_source {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContextSource;
        impl $crate::ContextSourceProvider for $plugin {
        fn read_resource(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::ReadResourceRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceReadResource> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_resource(&plugin, context, request).await;
                $crate::__LensoIntoContextSourceReadResourceResult::__lenso_into_result(result)
            })
        }
        fn render_prompt(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::RenderPromptRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceRenderPrompt> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::render_prompt(&plugin, context, request).await;
                $crate::__LensoIntoContextSourceRenderPromptResult::__lenso_into_result(result)
            })
        }
        fn snapshot(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::SnapshotRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceSnapshot> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::snapshot(&plugin, context, request).await;
                $crate::__LensoIntoContextSourceSnapshotResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_context_source {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContextSource;
        impl $crate::ContextSourceProvider for $object {
        fn read_resource(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::ReadResourceRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceReadResource> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_resource(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoContextSourceReadResourceResult::__lenso_into_result(result)
            })
        }
        fn render_prompt(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::RenderPromptRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceRenderPrompt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::render_prompt(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoContextSourceRenderPromptResult::__lenso_into_result(result)
            })
        }
        fn snapshot(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::SnapshotRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceSnapshot> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::snapshot(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoContextSourceSnapshotResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_context_source {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContextSource;
        impl $crate::ContextSourceProvider for $object {
        fn read_resource(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::ReadResourceRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceReadResource> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ContextSourceProvider>::read_resource(plugin.as_ref(), context, request).await
            })
        }
        fn render_prompt(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::RenderPromptRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceRenderPrompt> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ContextSourceProvider>::render_prompt(plugin.as_ref(), context, request).await
            })
        }
        fn snapshot(&self, context: __LensoNativeSupportContextSource::InvocationContext, request: $crate::SnapshotRequest) -> __LensoNativeSupportContextSource::NativeRequestFuture<$crate::ContextSourceSnapshot> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ContextSourceProvider>::snapshot(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ContextSourceRequestEndpoint { provider: Rc<dyn ContextSourceProvider> }

#[derive(Debug)]
pub struct ContextSourceEndpoint<P: ContextSourceProvider> { provider: Rc<P>, request_endpoint: ContextSourceRequestEndpoint }
impl<P: ContextSourceProvider> ContextSourceEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ContextSourceProvider> = provider.clone();
        Self { provider, request_endpoint: ContextSourceRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ContextSourceProvider> NativeRequestEndpoint for ContextSourceEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_RESOURCE_OPERATION,
        RENDER_PROMPT_OPERATION,
        SNAPSHOT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_RESOURCE_OPERATION => {
                let Ok(request) = request.downcast::<ReadResourceRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_resource(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RENDER_PROMPT_OPERATION => {
                let Ok(request) = request.downcast::<RenderPromptRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).render_prompt(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SNAPSHOT_OPERATION => {
                let Ok(request) = request.downcast::<SnapshotRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).snapshot(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_context_source {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ContextSourceEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_context_source {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_context_source!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct ContextSourceClient {
    read_resource: NativeRequestHandle<ContextSourceReadResource>,
    render_prompt: NativeRequestHandle<ContextSourceRenderPrompt>,
    snapshot: NativeRequestHandle<ContextSourceSnapshot>,
}
impl ContextSourceClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read_resource(&self, request: ReadResourceRequest) -> Result<ReadResourceResponse, ContextSourceReadResourceInvocationError> {
        self.read_resource.invoke(READ_RESOURCE_OPERATION, request).await
            .map_err(ContextSourceReadResourceInvocationError::Runtime)?
            .map_err(ContextSourceReadResourceInvocationError::Domain)
    }

    pub async fn read_resource_with_context(&self, context: InvocationContext, request: ReadResourceRequest) -> Result<ReadResourceResponse, ContextSourceReadResourceInvocationError> {
        self.read_resource.invoke_with_context(READ_RESOURCE_OPERATION, context, request).await
            .map_err(ContextSourceReadResourceInvocationError::Runtime)?
            .map_err(ContextSourceReadResourceInvocationError::Domain)
    }

    pub async fn render_prompt(&self, request: RenderPromptRequest) -> Result<RenderPromptResponse, ContextSourceRenderPromptInvocationError> {
        self.render_prompt.invoke(RENDER_PROMPT_OPERATION, request).await
            .map_err(ContextSourceRenderPromptInvocationError::Runtime)?
            .map_err(ContextSourceRenderPromptInvocationError::Domain)
    }

    pub async fn render_prompt_with_context(&self, context: InvocationContext, request: RenderPromptRequest) -> Result<RenderPromptResponse, ContextSourceRenderPromptInvocationError> {
        self.render_prompt.invoke_with_context(RENDER_PROMPT_OPERATION, context, request).await
            .map_err(ContextSourceRenderPromptInvocationError::Runtime)?
            .map_err(ContextSourceRenderPromptInvocationError::Domain)
    }

    pub async fn snapshot(&self, request: SnapshotRequest) -> Result<SnapshotResponse, ContextSourceSnapshotInvocationError> {
        self.snapshot.invoke(SNAPSHOT_OPERATION, request).await
            .map_err(ContextSourceSnapshotInvocationError::Runtime)?
            .map_err(ContextSourceSnapshotInvocationError::Domain)
    }

    pub async fn snapshot_with_context(&self, context: InvocationContext, request: SnapshotRequest) -> Result<SnapshotResponse, ContextSourceSnapshotInvocationError> {
        self.snapshot.invoke_with_context(SNAPSHOT_OPERATION, context, request).await
            .map_err(ContextSourceSnapshotInvocationError::Runtime)?
            .map_err(ContextSourceSnapshotInvocationError::Domain)
    }
}

impl CapabilityClient for ContextSourceClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_resource: dependencies.one::<ContextSourceReadResource>()?,
            render_prompt: dependencies.one::<ContextSourceRenderPrompt>()?,
            snapshot: dependencies.one::<ContextSourceSnapshot>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ContextSourceClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_resource: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContextSourceReadResource>()?,
                    render_prompt: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContextSourceRenderPrompt>()?,
                    snapshot: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ContextSourceSnapshot>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ContextSourceReadResourceInvocationError {
    Domain(ReadResourceError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContextSourceRenderPromptInvocationError {
    Domain(RenderPromptError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ContextSourceSnapshotInvocationError {
    Domain(SnapshotError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ContextSourceGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ContextSourceGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[READ_RESOURCE_OPERATION, RENDER_PROMPT_OPERATION, SNAPSHOT_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn read_resource(&self, request: &ReadResourceRequest) -> Result<ReadResourceResponse, lenso_guest_sdk::GuestError<ReadResourceError>> {
        self.capability.request(READ_RESOURCE_OPERATION, request)
    }

    pub fn render_prompt(&self, request: &RenderPromptRequest) -> Result<RenderPromptResponse, lenso_guest_sdk::GuestError<RenderPromptError>> {
        self.capability.request(RENDER_PROMPT_OPERATION, request)
    }

    pub fn snapshot(&self, request: &SnapshotRequest) -> Result<SnapshotResponse, lenso_guest_sdk::GuestError<SnapshotError>> {
        self.capability.request(SNAPSHOT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ContextSourceJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ContextSourceJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[READ_RESOURCE_OPERATION, RENDER_PROMPT_OPERATION, SNAPSHOT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            READ_RESOURCE_OPERATION => {
                let value = request.downcast_ref::<ReadResourceRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            RENDER_PROMPT_OPERATION => {
                let value = request.downcast_ref::<RenderPromptRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            SNAPSHOT_OPERATION => {
                let value = request.downcast_ref::<SnapshotRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_RESOURCE_OPERATION => serde_json::from_value::<ReadResourceResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RENDER_PROMPT_OPERATION => serde_json::from_value::<RenderPromptResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            SNAPSHOT_OPERATION => serde_json::from_value::<SnapshotResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_RESOURCE_OPERATION => serde_json::from_value::<ReadResourceError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RENDER_PROMPT_OPERATION => serde_json::from_value::<RenderPromptError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            SNAPSHOT_OPERATION => serde_json::from_value::<SnapshotError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            READ_RESOURCE_OPERATION => {
                let request = serde_json::from_value::<ReadResourceRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ContextSourceReadResource>()?;
                    match handle.invoke_with_context(READ_RESOURCE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            RENDER_PROMPT_OPERATION => {
                let request = serde_json::from_value::<RenderPromptRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ContextSourceRenderPrompt>()?;
                    match handle.invoke_with_context(RENDER_PROMPT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            SNAPSHOT_OPERATION => {
                let request = serde_json::from_value::<SnapshotRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ContextSourceSnapshot>()?;
                    match handle.invoke_with_context(SNAPSHOT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
