// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.agent.workspace-read@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const WORKSPACE_READ_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const WORKSPACE_READ_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_workspace_read { () => { "{\"capability_id\":\"lenso.agent.workspace-read@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"read_text\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_workspace_read_client { () => { "{\"capability_id\":\"lenso.agent.workspace-read@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_workspace_read_client { () => { "{\"capability_id\":\"lenso.agent.workspace-read@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const READ_TEXT_OPERATION: &str = "read_text";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTextRequest {
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTextResponse {
    #[serde(rename = "content")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content: String,
    #[serde(rename = "metadata_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub metadata_json: RawJson,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTextErrorExecutionFailedPayload {
    #[serde(rename = "details_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub details_json: RawJson,
    #[serde(rename = "message")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub message: String,
    #[serde(rename = "reason_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason_code: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadTextError {
    ExecutionFailed { payload: ReadTextErrorExecutionFailedPayload },
    InvalidArguments,
    NotFound,
    OutputLimitExceeded,
    PermissionDenied,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct WorkspaceRead;
impl RequestCapability for WorkspaceRead {
    type Request = ReadTextRequest;
    type Response = ReadTextResponse;
    type DomainError = ReadTextError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_TEXT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkspaceReadRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_text(context, request)
    }
}

impl serde::Serialize for ReadTextError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExecutionFailed { payload } => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("code", "execution_failed")?;
                map.serialize_entry("payload", payload)?;
                map.end()
            },
            Self::InvalidArguments => serializer.serialize_str("invalid_arguments"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::OutputLimitExceeded => serializer.serialize_str("output_limit_exceeded"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadTextError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_arguments" => Ok(Self::InvalidArguments),
                "not_found" => Ok(Self::NotFound),
                "output_limit_exceeded" => Ok(Self::OutputLimitExceeded),
                "permission_denied" => Ok(Self::PermissionDenied),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                match code.as_str() {
                    "execution_failed" => {
                        let payload = object.remove("payload").ok_or_else(|| serde::de::Error::custom("structured Domain Error is missing a payload"))?;
                        let payload = serde_json::from_value(payload).map_err(serde::de::Error::custom)?;
                        Ok(Self::ExecutionFailed { payload })
                    },
                    _ => {
                        let payload = object.remove("payload");
                        let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                        Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
                    }
                }
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_text_request(value: &ReadTextRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_text_request(wire: &str) -> Result<ReadTextRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_text_response(value: &ReadTextResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_text_response(wire: &str) -> Result<ReadTextResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_text_error(value: &ReadTextError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_text_error(wire: &str) -> Result<ReadTextError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoWorkspaceReadReadTextResult {
    fn __lenso_into_result(self) -> Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure>;
}
impl __LensoIntoWorkspaceReadReadTextResult for Result<ReadTextResponse, ReadTextError> {
    fn __lenso_into_result(self) -> Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkspaceReadReadTextResult for Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkspaceReadReadTextResult for Result<ReadTextResponse, lenso_plugin_authoring::PluginError<ReadTextError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkspaceReadReadTextResult for Result<ReadTextResponse, WorkspaceReadInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadTextResponse, ReadTextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkspaceReadInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkspaceReadInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait WorkspaceReadProvider: fmt::Debug + 'static {
    fn read_text(&self, context: InvocationContext, request: ReadTextRequest) -> NativeRequestFuture<WorkspaceRead>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_workspace_read {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportWorkspaceRead;
        impl $crate::WorkspaceReadProvider for $plugin {
        fn read_text(&self, context: __LensoNativeSupportWorkspaceRead::InvocationContext, request: $crate::ReadTextRequest) -> __LensoNativeSupportWorkspaceRead::NativeRequestFuture<$crate::WorkspaceRead> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_text(&plugin, context, request).await;
                $crate::__LensoIntoWorkspaceReadReadTextResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct WorkspaceReadRequestEndpoint { provider: Rc<dyn WorkspaceReadProvider> }

#[derive(Debug)]
pub struct WorkspaceReadEndpoint<P: WorkspaceReadProvider> { provider: Rc<P>, request_endpoint: WorkspaceReadRequestEndpoint }
impl<P: WorkspaceReadProvider> WorkspaceReadEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn WorkspaceReadProvider> = provider.clone();
        Self { provider, request_endpoint: WorkspaceReadRequestEndpoint { provider: request_provider } }
    }
}

impl<P: WorkspaceReadProvider> NativeRequestEndpoint for WorkspaceReadEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_TEXT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_TEXT_OPERATION => {
                let Ok(request) = request.downcast::<ReadTextRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_text(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_workspace_read {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::WorkspaceReadEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_workspace_read {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_workspace_read!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct WorkspaceReadClient {
    read_text: NativeRequestHandle<WorkspaceRead>,
}
impl WorkspaceReadClient {
    pub fn new(handle: NativeRequestHandle<WorkspaceRead>) -> Self {
        Self { read_text: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn read_text(&self, request: ReadTextRequest) -> Result<ReadTextResponse, WorkspaceReadInvocationError> {
        self.read_text.invoke(READ_TEXT_OPERATION, request).await
            .map_err(WorkspaceReadInvocationError::Runtime)?
            .map_err(WorkspaceReadInvocationError::Domain)
    }

    pub async fn read_text_with_context(&self, context: InvocationContext, request: ReadTextRequest) -> Result<ReadTextResponse, WorkspaceReadInvocationError> {
        self.read_text.invoke_with_context(READ_TEXT_OPERATION, context, request).await
            .map_err(WorkspaceReadInvocationError::Runtime)?
            .map_err(WorkspaceReadInvocationError::Domain)
    }
}

impl CapabilityClient for WorkspaceReadClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_text: dependencies.one::<WorkspaceRead>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for WorkspaceReadClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_text: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkspaceRead>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum WorkspaceReadInvocationError {
    Domain(ReadTextError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct WorkspaceReadGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> WorkspaceReadGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[READ_TEXT_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn read_text(&self, request: &ReadTextRequest) -> Result<ReadTextResponse, lenso_guest_sdk::GuestError<ReadTextError>> {
        self.capability.request(READ_TEXT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct WorkspaceReadJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for WorkspaceReadJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn request_operations(&self) -> &'static [&'static str] { &[READ_TEXT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            READ_TEXT_OPERATION => {
                let value = request.downcast_ref::<ReadTextRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_TEXT_OPERATION => serde_json::from_value::<ReadTextResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_TEXT_OPERATION => serde_json::from_value::<ReadTextError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            READ_TEXT_OPERATION => {
                let request = serde_json::from_value::<ReadTextRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<WorkspaceRead>()?;
                    match handle.invoke_with_context(READ_TEXT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
